import type { PublicGuideContent, PublicGuideEntry, PublicGuideLanguage } from "./public-guide-library";
import { getPracticalFoodExample } from "./practical-food-examples";
import { getSoilGuideContent } from "./soil-guide-content";

// Editorial fallbacks for platform presets only. Never rewrite a user's guide,
// taxonomy, project name, or stored content. Quantities that depend on species,
// engineering specifications, or a validated food process are not invented here.
type TextPair = readonly [zh: string, en: string];
type Steps = readonly [overview: string, start: string, care: string, issue: string];
type Kind = "soil" | "compost" | "structure" | "climate" | "water" | "housing" | "aquaticPlant" | "fish" | "marine" | "invertebrate" | "landSnail" | "amphibian" | "reptile" | "insect" | "wildlife" | "petBird" | "poultry" | "rabbit" | "livestock" | "food" | "ferment" | "brew";
type Profile = { kind: Kind; zh: Steps; en: Steps };
const profile = (kind: Kind, zh: Steps, en: Steps): Profile => ({ kind, zh, en });
const localize = (text: TextPair, language: PublicGuideLanguage) => text[language === "en" ? 1 : 0];

const references = {
  soil: { title: "UMN Extension · Soil testing", url: "https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/soil-testing-for-lawns-and-gardens" },
  compost: { title: "EPA · Composting at home", url: "https://www.epa.gov/recycle/composting-home" },
  structure: { title: "UMN Extension · Living soil, healthy garden", url: "https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-minnesota/living-soil-healthy-garden" },
  climate: { title: "RHS · Greenhouse ventilation and shading", url: "https://www.rhs.org.uk/garden-features/ventilation-and-shading-greenhouses" },
  water: { title: "RHS · Collecting and storing water", url: "https://www.rhs.org.uk/garden-jobs/water-collecting-storing-and-using" },
  aquaticPlant: { title: "Tropica · Planting in the aquarium", url: "https://tropica.com/en/guide/get-the-right-start/planting/" },
  fish: { title: "OATA · Freshwater aquarium care", url: "https://ornamentalfish.org/what-we-do/advice-information/care-sheets/caresheets-tropical-freshwater-fish/how-to-set-up-and-look-after-a-freshwater-tank-aquarium/" },
  marine: { title: "OATA · Marine aquarium care", url: "https://ornamentalfish.org/what-we-do/advice-information/care-sheets/caresheets-marine-fish/how-to-set-up-and-look-after-a-marine-tank-aquarium/" },
  animal: { title: "RSPCA · Caring for exotic pets", url: "https://www.rspca.org.uk/adviceandwelfare/pets/other" },
  terrapin: { title: "RSPCA · Terrapin care", url: "https://www.rspca.org.uk/adviceandwelfare/pets/other/terrapin" },
  wildlife: { title: "RHS · Wildlife in gardens", url: "https://www.rhs.org.uk/wildlife/in-gardens" },
  butterfly: { title: "RHS · Butterflies in the garden", url: "https://www.rhs.org.uk/wildlife/butterflies-in-your-garden" },
  bird: { title: "Cornell Lab · Window collisions and injured birds", url: "https://www.allaboutbirds.org/news/why-birds-hit-windows-and-how-you-can-help-prevent-it/" },
  poultry: { title: "UMN Extension · Raising chickens", url: "https://extension.umn.edu/agriculture/animals-and-livestock/poultry/raising-chickens-for-eggs" },
  rabbit: { title: "RSPCA · Rabbit health checks", url: "https://www.rspca.org.uk/adviceandwelfare/pets/rabbits/health" },
  livestock: { title: "UMN Extension · Monitoring pigs' water intake", url: "https://extension.umn.edu/agriculture/animals-and-livestock/swine/using-water-intake-monitor-pig-performance" },
  food: { title: "NCHFP · Tested home-preservation methods", url: "https://nchfp.uga.edu/how/pickle/general-information-pickling/general-information-on-pickling/" },
  jam: { title: "NCHFP · Tested plum-jam recipe", url: "https://nchfp.uga.edu/how/make-jam-jelly/jams/plum-jam-pectin/" },
  ferment: { title: "NCHFP · Fermentation controls", url: "https://nchfp.uga.edu/how/ferment/general-information-on-fermenting/" },
  tofu: { title: "Centre for Food Safety · Safe bean-curd preparation", url: "https://www.cfs.gov.hk/english/multimedia/multimedia_pub/multimedia_pub_fsf_239_02.html" },
  juice: { title: "FDA · Juice safety", url: "https://www.fda.gov/food/buy-store-serve-safe-food/what-you-need-know-about-juice-safety" },
  dry: { title: "MSU Extension · Drying fruits", url: "https://extension-store.montana.edu/montguides/drying-fruits" },
  horse: { title: "Merck Veterinary Manual · Colic signs in horses", url: "https://www.merckvetmanual.com/horse-owners/digestive-disorders-of-horses/colic-in-horses" },
  sheep: { title: "Merck Veterinary Manual · Copper sensitivity", url: "https://www.merckvetmanual.com/toxicology/copper-toxicosis/copper-toxicosis-in-animals" },
} as const;
type ReferenceKey = keyof typeof references;

type Routine = { start: TextPair; care: TextPair; reminder: TextPair; caution: TextPair; references: ReferenceKey[] };
const routines: Record<Kind, Routine> = {
  soil: {
    start: ["划出一小块试验区，拍下表土、根系和雨后积水；留一块不处理的区域作对照。", "Mark a trial patch and an untreated comparison; photograph soil, roots, and pooling after rain."],
    care: ["每次只改一个因素，记下材料、用量、范围和日期，再比较渗水与长势。", "Change one factor at a time and record material, amount, area, and date before comparing drainage and growth."],
    reminder: ["大雨后查排水；种植前复核土壤检测结果和上轮添加量，不按日历反复施肥。", "Check drainage after heavy rain; review soil tests and previous additions before planting rather than fertilizing by calendar alone."],
    caution: ["来历不明的土和疑似污染地块先检测；不要凭叶色直接加石灰、硫磺或大量肥料。", "Test unknown or potentially contaminated soil; leaf color alone is not a reason to add lime, sulfur, or heavy fertilizer."],
    references: ["soil"],
  },
  compost: {
    start: ["把干叶、碎纸板等干料与果蔬残渣分开放；家庭冷堆先不放肉、油脂、宠物粪便和病株。", "Keep dry leaves/cardboard and fruit/vegetable scraps separately; leave meat, fats, pet waste, and diseased plants out of a simple home pile."],
    care: ["翻看内部而不只看表面：湿润但不滴水，结块就打散；新增厨余后盖干料。", "Check the center, not just the surface: keep it moist but not dripping, break clumps, and cover new scraps with dry material."],
    reminder: ["每次投料查湿度和气味；停止投料后另留熟化期，土腥味、疏松、原料难辨时再检查是否可用。", "Check moisture and odor at each addition; allow a separate curing period and inspect texture, earthy smell, and remaining scraps before use."],
    caution: ["不升温不等于失败；未经验证的家庭堆肥不能保证杀死病原或杂草种子。", "A cool pile is not automatically a failure; an unverified home process cannot guarantee destruction of pathogens or weed seeds."],
    references: ["compost"],
  },
  structure: {
    start: ["按产品说明核对满载重量、连接件和固定方式；先空载装好，再分次放入湿土或花盆。", "Check the product's loaded-weight rating, fasteners, and anchoring; assemble empty and add wet soil or pots in stages."],
    care: ["浇水后检查支脚、接缝和地面积水；固定同一角度拍照，便于发现歪斜和下沉。", "After watering, inspect feet, joints, and standing water; repeat photos from one angle to reveal tilt or settlement."],
    reminder: ["增加花盆、移动位置和大风后重新检查；发现松动先卸载再修复。", "Recheck after adding pots, moving, or strong wind; unload a loose structure before repair."],
    caution: ["阳台、屋顶和悬挂设施的承重不能靠目测确认；不明承重时先让专业人员核实。", "Balcony, roof, and hanging loads cannot be judged by appearance; obtain a qualified assessment where capacity is unknown."],
    references: [],
  },
  climate: {
    start: ["在植物高度放温湿度计，记录晴天午后和夜间读数；留出可操作的通风口。", "Place a thermometer/hygrometer at plant height; record sunny-afternoon and nighttime readings and keep vents accessible."],
    care: ["把开关棚、通风、遮阳的时间与读数一起记下，先试小范围调整。", "Log venting, covering, and shading alongside readings; try changes on a small area first."],
    reminder: ["晴天升温前查通风；寒潮、大风前核对固定件和覆盖层，天气过后复查。", "Check ventilation before sunny-day heating; inspect fixings and covers before and after cold or windy weather."],
    caution: ["密闭保温可能同时积热、积湿；用电加温遵守设备的防水、间距及防火要求。", "A closed cover can trap heat and moisture; electric heating must follow equipment requirements for water protection, clearance, and fire safety."],
    references: ["climate"],
  },
  water: {
    start: ["画出水源、阀门、过滤、出水和溢流的简图，标出能关闭和清洗的位置。", "Sketch the supply, valves, filters, outlets, and overflow; mark accessible shutoffs and cleaning points."],
    care: ["先用清水试运行，沿途查看漏水、堵塞和回流；记下正常水位或流量作为对照。", "Test with clean water, check leaks, blockages, and backflow, and record normal level or flow for comparison."],
    reminder: ["启用、清洗和长时间停用后都试运行；大雨、冰冻、停电后检查溢流和连接。", "Test after commissioning, cleaning, and long shutdowns; check overflow and connections after rain, frost, or power loss."],
    caution: ["储水不是饮用水处理；水电作业先断电，水箱和池面需防儿童及动物跌入。", "Storage is not drinking-water treatment; isolate power for wet maintenance and protect tanks/ponds from falls by children and animals."],
    references: ["water"],
  },
  housing: {
    start: ["从动物视角检查门缝、尖角、夹脚处和可啃咬电线；人要能方便清洁和紧急开门。", "Check gaps, sharp edges, foot traps, and reachable wires from the animal's level; keep cleaning and emergency access practical."],
    care: ["每天检查门锁、饮水处湿垫料和排泄区；先移开动物再维修或使用清洁剂。", "Check latches, wet bedding near drinkers, and waste areas daily; move animals away before repairs or cleaners."],
    reminder: ["换季、暴雨和增加动物后重查遮阴、通风、干燥及防逃逸。", "Review shade, airflow, dryness, and escape protection after seasonal changes, rain, or adding animals."],
    caution: ["空间按成年体型和实际数量设计，不把幼体能住当作长期合适；避免仅靠细网防大型天敌。", "Design for adult size and actual numbers; juvenile fit is not lifetime suitability, and fine mesh alone may not stop larger predators."],
    references: [],
  },
  aquaticPlant: {
    start: ["保留购买标签或学名；清除运输包装，先把种植位置和入缸状态拍下来。", "Keep the label or scientific name, remove transport packaging, and photograph the planting position and arrival condition."],
    care: ["每周同角度拍新芽和老叶；修剪后捞净碎叶，记下光照、施肥或换水的单项变化。", "Photograph new and old leaves weekly; remove pruning debris and log individual changes in light, nutrients, or water."],
    reminder: ["刚定植时先检查是否松脱；修剪、移动灯具或换水后，连续观察新叶而不只看旧叶。", "Check for loose plants after planting; following pruning, light changes, or water changes, track new growth as well as old leaves."],
    caution: ["俗名可能对应不同物种；不要凭名称套用统一水温。修剪物不要丢进河道或户外水体。", "Trade names can cover different species; do not assume one temperature from a name. Keep trimmings out of natural waterways."],
    references: ["aquaticPlant"],
  },
  fish: {
    start: ["入鱼前用检测确认过滤系统能处理氨和亚硝酸盐，不以水清或开机天数代替检测。", "Before stocking, use tests to confirm the filter handles ammonia and nitrite; clear water or elapsed days are not proof."],
    care: ["每天先观察呼吸、游姿和摄食再投喂；记下剩饵和换水量，换水时匹配新水条件。", "Observe breathing, swimming, and appetite before feeding; log leftovers and water changes and match replacement-water conditions."],
    reminder: ["新入鱼、过滤维护或停电后增加水质检查；离家前确认有人能查看设备和动物。", "Increase water checks after additions, filter work, or power loss; arrange equipment and animal checks before travel."],
    caution: ["异常先查水质和设备；持续呼吸困难、损伤或不进食应联系水生动物兽医，不混用药物试错。", "Check water and equipment first; persistent breathing difficulty, injury, or refusal to feed needs aquatic-veterinary advice, not mixed treatments."],
    references: ["fish"],
  },
  marine: {
    start: ["用水族海盐配制新水，单独混匀并测盐度、水温；食盐水不能替代海水。", "Prepare replacement water separately with aquarium marine salt, then measure salinity and temperature; table salt is not a substitute."],
    care: ["区分蒸发补水与换水：按实际盐度纠偏，补蒸发水前先核对仪表和水位。", "Distinguish evaporation top-ups from water changes; check the instrument, level, and salinity before correction."],
    reminder: ["每天看水位、循环和动物呼吸；换水或增加生物前后复测盐度和氮废物。", "Check level, circulation, and breathing daily; retest salinity and nitrogen waste around water changes and stocking."],
    caution: ["珊瑚、鱼和无脊椎动物的兼容性需分别核对；不根据气泡或水色判断水质安全。", "Check compatibility separately for fish, corals, and invertebrates; bubbles or water color do not establish safety."],
    references: ["marine"],
  },
  invertebrate: {
    start: ["购买前确认准确种名、淡水或海水及是否需要陆地区；准备可独立观察的空间。", "Confirm the species, freshwater/marine requirements, and any land area before purchase; prepare a separate observation space."],
    care: ["观察活动、摄食和躲藏点，清走剩食；更换水或添加药剂前先核对对该物种是否适用。", "Check activity, feeding, and hiding places and remove leftovers; verify species suitability before water additives or medication."],
    reminder: ["新入缸、蜕壳或同伴数量变化后增加巡查，记录日期和所做调整。", "Increase checks after introduction, molts, or changes in companions; record dates and adjustments."],
    caution: ["不要把清洁缸壁或吃残渣理解为不需要喂养，也不要放生或倾倒活体到自然水体。", "Grazing algae or scraps does not mean no feeding is needed; never release animals into natural water."],
    references: ["fish"],
  },
  landSnail: {
    start: ["先在原处观察，若饲养需确认来源与物种；准备通风、防逃逸且无农药残留的容器。", "Prefer observation in place; for kept animals confirm species/source and use a ventilated, escape-resistant, pesticide-free enclosure."],
    care: ["每天移走变质食物并检查角落积水、霉点和盖子；洗手后再接触用具。", "Remove spoiled food and check corners for pooling, mold, and lid gaps daily; wash hands when handling equipment."],
    reminder: ["高温、干燥或更换基质后查看活动变化；保留湿度差异，不让整个容器积水。", "Watch activity after heat, dry weather, or substrate changes; offer a moisture gradient without flooding the enclosure."],
    caution: ["不徒手接触黏液后揉眼或拿食物；野采个体不要混入家庭饲养群。", "Avoid touching eyes or food after contact with mucus; do not mix wild-caught individuals into kept groups."],
    references: ["wildlife"],
  },
  amphibian: {
    start: ["先确认生活阶段和物种；分别检查水区、陆区与出水坡道，不能只按“蛙类”设置。", "Identify species and life stage; check water, land, and exit routes rather than using a single frog setup."],
    care: ["少接触皮肤，清走残饵；每天从外部观察姿态、体表和水区状态。", "Minimize skin contact and remove leftovers; observe posture, skin, and water conditions from outside each day."],
    reminder: ["变态、季节变化和拒食时复核栖息条件；异常记录照片供专业人员判断。", "Review conditions at metamorphosis, seasonal changes, or appetite loss; photograph abnormalities for professional advice."],
    caution: ["不抓野生个体回家混养；持续失衡、皮肤病变或明显消瘦应咨询异宠兽医。", "Do not collect wild animals for mixed housing; persistent imbalance, skin lesions, or weight loss needs an exotics vet."],
    references: ["animal"],
  },
  reptile: {
    start: ["在动物实际停留处测量温度；加热设备用合适的温控和防接触保护，不只读房间温度。", "Measure where the animal actually rests; use suitable thermostats and contact guards, not room temperature alone."],
    care: ["每天检查饮水、排泄、活动与设备；换灯或移动晒台后重新测量，不照搬旧距离。", "Check water, droppings, behavior, and equipment daily; remeasure after moving a basking site or replacing a lamp."],
    reminder: ["保留设备说明、灯具启用日期和体重趋势；换季先复核种类需要，不自行安排冬眠。", "Keep equipment instructions, lamp start dates, and weight trends; review species needs seasonally rather than initiating hibernation yourself."],
    caution: ["先确定物种再选食物、温度和UVB方案；呼吸异常、持续拒食或外伤需异宠兽医，指引不提供用药剂量。", "Identify the species before choosing food, temperatures, or UVB; breathing problems, persistent refusal to eat, or injuries need an exotics vet. No drug doses are supplied here."],
    references: ["animal"],
  },
  insect: {
    start: ["拍下成体或幼体特征、发现植物和日期，先确认对象及生活阶段。", "Photograph identifying features, host plant, and date; establish the organism and life stage first."],
    care: ["用短时观察代替频繁翻动，记录取食、蜕变和所处植物；及时清除饲养容器中的腐败物。", "Use brief observation instead of repeated disturbance; log feeding, molts, and host plants and remove decaying material from kept enclosures."],
    reminder: ["蜕皮、化蛹或羽化前后减少触碰；变化当天拍照记录，而非按固定天数催促。", "Minimize handling around molts, pupation, and emergence; record the actual change rather than forcing a calendar."],
    caution: ["不能可靠识别、有毒或有蜇伤风险的种类以远距离观察为主；不跨地区释放饲养个体。", "Observe unidentified, venomous, or stinging organisms from a distance; do not release captive individuals in other regions."],
    references: ["wildlife"],
  },
  wildlife: {
    start: ["在原处选固定观察点，不抓捕、不搬巢，也不为了照片驱赶动物。", "Choose a fixed observation point in place; do not capture, move nests, or drive animals for a photo."],
    care: ["记录时间、天气、数量与行为；保持观察距离，减少夜灯、噪声和宠物追逐。", "Log time, weather, number, and behavior; keep distance and reduce night lighting, noise, and pet chasing."],
    reminder: ["繁殖或育幼期减少靠近；受伤个体先联系当地野生动物救助机构。", "Increase distance during nesting or rearing; contact a local wildlife rehabilitator for injured animals."],
    caution: ["不要把暂时停留或幼鸟离巢当作被遗弃；不强行喂水、喂奶或饲喂人类饭菜。", "Resting or fledging is not automatically abandonment; do not force water, milk, or human meals."],
    references: ["wildlife", "bird"],
  },
  petBird: {
    start: ["确认品种、成年体型和原来的食物；安排安静观察区及可安全活动的空间。", "Confirm species, adult size, and previous diet; prepare a quiet observation area and safe activity space."],
    care: ["每天清洗饮水器，查看食量、粪便和站姿；清洁时检查栖架、门扣和可误食小件。", "Clean drinkers and check intake, droppings, and posture daily; inspect perches, latches, and swallowable parts."],
    reminder: ["换食物逐步进行并称量摄食；持续蓬羽、呼吸困难或突然不进食应尽快联系鸟类兽医。", "Change diet gradually while measuring intake; persistent fluffed posture, breathing difficulty, or sudden appetite loss needs prompt avian-vet advice."],
    caution: ["不要靠抓握或限制饮食纠正行为；避免厨房烟气、开放窗户和宠物接触风险。", "Do not use force or food deprivation to correct behavior; avoid kitchen fumes, open-window escapes, and unsafe pet contact."],
    references: ["animal"],
  },
  poultry: {
    start: ["按年龄选择完整饲料，设置每只都能到达的饮水和进食位置；新来个体先单独观察。", "Use a complete age-appropriate feed, accessible feeding/watering points, and separate observation for newcomers."],
    care: ["每天查水和采食，移走湿垫料；黄昏清点并关好舍门，记录产蛋和异常粪便。", "Check water and feed daily, remove wet bedding, count and secure birds at dusk, and log eggs and unusual droppings."],
    reminder: ["高温、换羽、转群和饲料变更时增加巡查；准备离家期间的照护交接。", "Increase checks during heat, molting, flock moves, and feed changes; arrange care before travel."],
    caution: ["呼吸困难、多只同时发病或突然死亡应及时联系兽医；不凭网上配方给整群用药。", "Breathing difficulty, multiple sick birds, or sudden deaths need veterinary help; do not medicate a flock from an unverified recipe."],
    references: ["poultry"],
  },
  rabbit: {
    start: ["准备可持续取食的合适干草、清水、躲藏和活动区；食物更换分步进行。", "Provide suitable hay, fresh water, hiding places, and exercise space; change foods gradually."],
    care: ["每天确认实际进食和排便，检查臀部、足底及饮水器是否正常出水。", "Confirm eating and droppings each day and check the rear, feet, and functioning drinker."],
    reminder: ["每天同一时段观察；不吃或便量明显减少不要等到下一次例行检查，应尽快联系兽医。", "Observe at the same time daily; not eating or a marked drop in droppings needs prompt veterinary advice, not the next routine check."],
    caution: ["不要把兔子当小型家禽喂养；不自行用人药或强迫灌食不明原因拒食的个体。", "Rabbits are not small poultry; do not use human medicines or force-feed unexplained appetite loss without veterinary direction."],
    references: ["rabbit"],
  },
  livestock: {
    start: ["按年龄、体况和繁殖阶段向当地兽医或饲养顾问确认日粮；新个体设独立观察区。", "Confirm the ration for age, condition, and reproductive stage with a local vet or nutrition adviser; separate newcomers for observation."],
    care: ["每天实际检查饮水是否流出、食槽余量、粪便和行走；不要只记录已投了多少料。", "Check that water actually flows, inspect feed leftovers, manure, and gait daily, rather than recording only feed offered."],
    reminder: ["高温、转栏、换料和临近生产时增加巡查；疫苗、驱虫及用药计划交由当地兽医制定。", "Increase checks during heat, moves, ration changes, and near birth; let a local vet set vaccination, parasite, and medicine plans."],
    caution: ["倒地、明显腹胀、呼吸困难或持续不采食应及时求助；大型动物操作需有安全退路。", "Collapse, marked bloating, breathing difficulty, or persistent appetite loss needs prompt help; keep an escape route when handling large animals."],
    references: [],
  },
  food: {
    start: ["称量原料并保存所用可靠配方；把容器、加工日期和冷藏方式写在记录里。", "Weigh ingredients and retain the reliable recipe; record the container, processing date, and refrigeration method."],
    care: ["按配方的完整流程操作，器具接触生料后重新清洁；分装时避免把旧批次混入新批次。", "Follow the complete method, clean utensils after raw ingredients, and do not mix an old batch into a new one."],
    reminder: ["制作和开封时各记一次日期；没有经过验证的常温保存工艺，就不要按罐头长期存放。", "Record both making and opening dates; without a validated shelf-stable process, do not treat the product as a long-life preserve."],
    caution: ["鼓盖、渗漏、霉变或保存条件不明时不要试吃；闻起来正常也不能证明安全。", "Do not taste swollen, leaking, moldy, or questionably stored food; a normal smell does not prove safety."],
    references: ["food"],
  },
  ferment: {
    start: ["开始前要有适用于该食品的明确菌种和经过验证的完整工艺；记录盐量、温度与容器，不凭口味减盐。", "Start only with an identified culture and a validated process for that food; record salt, temperature, and vessel, and do not reduce salt by taste."],
    care: ["每次检查先清洁工具；按原工艺管理液面、通气和温度，不边做边更换配方。", "Clean tools before checks and manage liquid level, aeration, and temperature according to the original method rather than changing recipes mid-process."],
    reminder: ["关键温度、时间或配比失控就停止作为可食用成品使用；不要把补盐、再煮或挑掉霉点当作补救。", "If critical time, temperature, or proportions fail, stop treating the batch as edible; extra salt, reheating, or removing mold is not a validated rescue."],
    caution: ["此页用于操作前核查和过程记录，不构成家庭自然发酵配方；缺少可靠工艺时选择有资质来源的成品。", "This is a preparation and process-check guide, not a spontaneous-fermentation recipe; choose a reputable finished product if a reliable process is unavailable."],
    references: ["ferment", "tofu"],
  },
  brew: {
    start: ["使用来源明确的发酵剂和配套工艺，称量糖或淀粉原料；气体排放装置按容器说明安装。", "Use an identified starter with its validated method, weigh sugar/starch ingredients, and fit venting according to the vessel instructions."],
    care: ["记录温度、投料和检测读数；有产气时不使用不耐压的密闭瓶，不凭气泡停止就认定可装瓶。", "Log temperature, additions, and readings; never seal active fermentation in a non-pressure-rated bottle or infer bottling readiness from bubbles alone."],
    reminder: ["装瓶前按工艺确认发酵终点；标注含酒精、日期和储存条件，不以口尝估计酒精度。", "Confirm the method's fermentation endpoint before bottling; label alcohol, date, and storage, and do not estimate alcohol by taste."],
    caution: ["不提供蒸馏、增压或不明菌种试酿方法；不向未成年人提供酒类，生产与分享前核对当地要求。", "No distillation, pressurization, or unknown-culture methods are provided; do not supply alcohol to minors and check local requirements before production or sharing."],
    references: ["ferment"],
  },
};

const facilityProfiles: Record<string, Profile> = {
  土壤改良: profile("soil", ["先分清板结、积水还是养分问题，再决定要不要加材料。", "雨后看积水位置；取多点混合土样送检，先拿到酸碱度和养分结果。", "表土易结壳时先减少踩踏、保留覆盖；试验区分次加腐熟有机物。", "越改越湿时先查排水出口与土层，不继续堆加细料。"], ["Separate compaction, drainage, and nutrient problems before adding materials.", "Map pooling after rain and submit a mixed, multi-point soil sample for pH and nutrient testing.", "Reduce trampling and retain cover where crusting occurs; trial mature organic matter incrementally.", "If soil becomes wetter, inspect outlets and layers before adding more fine material."]),
  堆肥: profile("compost", ["把投料、含水和通气做好，成熟后再接触植物根系。", "粗碎干料与湿料混合，湿厨余不要压成厚实一层；预留可翻动空间。", "有酸臭先翻松并补干料；太干则少量分次加水拌匀。", "停止加料后仍明显发热或能看到大量新鲜残渣，继续熟化，不直接作育苗土。"], ["Manage additions, moisture, and air, then cure before contact with roots.", "Mix shredded dry and wet materials without compact layers of scraps; leave turning access.", "For sour odors, loosen and add dry material; if dry, mix in water gradually.", "If a closed batch still heats strongly or contains many fresh scraps, keep curing rather than using it as seedling medium."]),
  种植箱: profile("structure", ["重点是湿土承重、排水口和今后的清理通道。", "填土前试注清水，确认排水口畅通；垫高方式按箱体说明，不封死底孔。", "浇透后检查排水，移走接水盘长时间积水；随土沉降少量补基质。", "箱壁外鼓、底板变形或支脚下沉时先停止加土，卸载后检查。"], ["Plan for wet-soil load, open drainage, and cleaning access.", "Test drainage with clean water before filling; support the box as specified without blocking outlets.", "Check drainage after watering, clear standing saucer water, and top up settled medium gradually.", "Stop adding soil if walls bulge, the base distorts, or feet sink; unload before inspection."]),
  高床: profile("structure", ["让人能在通道完成种植，减少踩踏床内土壤。", "先在地面放样并试着够到中央，再装边框；保留通道和排水去向。", "从通道浇水、施肥和采收；观察土层沉降后再补料。", "床边冲刷或积水时查坡向和出口，不用加高边框掩盖问题。"], ["Make the bed reachable from paths so soil need not be walked on.", "Mark it on the ground and test reach before installing edges; retain paths and drainage routes.", "Water, feed, and harvest from paths; observe settlement before topping up.", "For erosion or pooling, inspect grade and outlets instead of simply raising the sides."]),
  育苗架: profile("structure", ["育苗架要同时解决盆盘重量、均匀光照和滴水。", "先放空育苗盘检查取放与灯距，装防倾倒固定；灯具按说明避开浇水路径。", "观察边缘和中央苗是否徒长；轮换盘位时一并检查积水。", "苗总向一侧倒先查光照；架体晃动或插座受潮先停用处理。"], ["Balance tray load, even light, and water management.", "Test empty-tray access and lamp clearance, anchor against tipping, and keep lighting clear of watering paths.", "Compare edge and center seedlings for stretching and check pooling when rotating trays.", "Check light for one-sided leaning; stop using a wobbling rack or damp electrical outlet."]),
  花架: profile("structure", ["按浇水后的花盆重量安排层位，重盆尽量放低。", "把最重花盆的湿重与架体额定值核对，留好接水和擦拭空间。", "取放花盆时检查脚垫和固定点，不拖拉带盆高架。", "出现锈蚀、裂纹或连接孔扩大时先卸盆，再判断维修或更换。"], ["Arrange shelves for wet-pot weight, keeping heavier pots low.", "Compare the heaviest wet pot with the stand rating and leave drainage and cleaning access.", "Check feet and fixings during pot changes; do not drag a tall loaded stand.", "Unload pots before assessing rust, cracks, or enlarged fixing holes."]),
  爬藤架: profile("structure", ["按成株、果实和大风后的负荷选架，不按幼苗重量选。", "立柱和横杆固定后再引蔓，用柔软绑带留出茎增粗空间。", "把新蔓分散引上架，及时松开勒茎绑带，保留采收通道。", "倾斜、根部松土或枝蔓集中一侧时先减轻局部负荷并重新固定。"], ["Size the support for mature growth, fruit, and wind, not seedlings.", "Secure posts and rails before training vines; use soft ties with room for stems to thicken.", "Spread new growth, loosen constricting ties, and keep harvest access.", "For tilt, loose post soil, or one-sided growth, reduce local load and secure the structure."]),
  温室: profile("climate", ["保温之外，更要防晴天积热和持续结露。", "确认门、侧窗和顶窗能开启，温度计避开直晒，并记录棚内冷热位置。", "晴天提早通风，结合植物萎蔫和实测温度调整遮阳；傍晚查看结露。", "土仍湿却萎蔫先看棚温和根部，不立刻追加大量水。"], ["Prevent sunny-day overheating and persistent condensation as well as retaining heat.", "Check doors and vents open, shade the sensor from direct sun, and map hot/cool spots.", "Vent early on sunny days and adjust shade using plant response and measured temperatures; check evening condensation.", "When plants wilt in wet soil, check heat and roots before adding much more water."]),
  保温棚: profile("climate", ["用覆盖减缓夜间失温，白天仍要能揭开散热。", "覆盖前检查支撑与压边，避免薄膜压伤嫩梢；留可快速开启的一侧。", "比较棚内外最低温；暖天及时通风，潮湿覆盖物晾干再收纳。", "叶片接触膜处受损或棚内滴水多，先调整间距和通风。"], ["Use covers to slow nighttime heat loss while retaining daytime ventilation.", "Check supports and secured edges, prevent film pressing on shoots, and keep one side easy to open.", "Compare indoor/outdoor minima; vent warm days and dry covers before storage.", "For contact damage or heavy dripping, adjust clearance and airflow first."]),
  遮阳棚: profile("climate", ["先观察被晒伤的时段，再决定遮哪里、遮多久。", "记录上午与午后日照方向，先遮最强时段；不要同时堵住通风面。", "比较新叶、节间与棚下温度，阴雨或季节转凉时重新评估遮阳。", "叶色变淡、枝条拉长时查是否遮得过多；不能靠继续施肥补光。"], ["Observe the damaging exposure period before deciding where and when to shade.", "Map morning/afternoon sun and shade the strongest period first without blocking airflow.", "Compare new leaves, internodes, and temperature; review shading in cloudy or cooler weather.", "For pale, stretched growth, check excessive shade instead of trying to replace light with fertilizer."]),
  防虫网棚: profile("climate", ["网棚靠完整封闭防虫，同时要兼顾通风和授粉。", "按要防的害虫选网，入棚苗先检查叶背；封好地面、门边和管线缝。", "每次出入关门，巡查破洞和网内害虫，开花时核对作物授粉需求。", "网内仍有虫时查带入苗和破口，不以更细网直接解决所有问题。"], ["Exclusion needs intact coverage while allowing airflow and pollination.", "Choose mesh for the target pest, inspect incoming plants, and seal ground, door, and pipe gaps.", "Close after entry, check tears and insects inside, and review pollination at flowering.", "If insects remain, inspect incoming stock and gaps rather than assuming finer mesh fixes everything."]),
  滴灌: profile("water", ["先验证每个滴头实际出水，再设定浇水时间。", "装好过滤器并冲洗管路，在首尾滴头下放相同容器，同时间接水比较。", "检查最远端与高处是否缺水，用土壤实际湿润深度调整时长。", "末端少水先查折管、过滤器和压力；局部堵头单独清理，不先延长全区浇水。"], ["Check actual emitter output before setting watering duration.", "Fit filtration, flush lines, and compare equal-time collection at the first and last emitters.", "Check distant/high points and adjust duration to the soil's actual wetting depth.", "For weak tail-end output, inspect kinks, filters, and pressure; clean local clogs instead of lengthening every zone."]),
  雨水收集: profile("water", ["让屋面杂物先被拦下，储水和溢流都有明确去向。", "清理集水面和落水管，装拦叶网；确认桶盖、溢流与可清洗入口。", "雨后查看杂物和水味，定期用掉存水，清洁时刷洗沉积物。", "水发臭或积泥明显时暂停使用并清洗；不把消毒剂随意倒进灌溉桶。"], ["Intercept roof debris and provide clear storage and overflow routes.", "Clean the catchment and gutter, fit a leaf screen, and check lid, overflow, and cleaning access.", "Inspect debris and odor after rain, use stored water regularly, and brush deposits during cleaning.", "Pause use and clean foul-smelling or muddy storage; do not casually add disinfectants to irrigation water."]),
  蓄水设施: profile("water", ["关注满水重量、遮光防污染和彻底排空能力。", "装水前核对基础承重，检查盖、排空阀、溢流管与水位标识。", "对照正常水位查不明下降，检查连接处渗漏；保留最近清洗日期。", "底座下沉、壁面裂纹或管件持续滴漏时停止补水并排查。"], ["Plan for full weight, contamination protection, and complete draining.", "Check the foundation rating, lid, drain valve, overflow, and level markings before filling.", "Compare normal levels for unexplained loss, inspect leaks, and retain the last cleaning date.", "Stop filling if the base settles, walls crack, or fittings continually leak."]),
  排水系统: profile("water", ["先看水从哪里来、在哪里停，不先挖一条无出口的沟。", "雨中或雨后画出积水线，检查已有出口；施工前核对地下管线。", "清理落叶和沉沙，检查检修口；用少量清水测试是否顺畅排出。", "清完又堵先找上游泥沙来源；持续积水或倒灌请专业人员检查坡度与容量。"], ["Map where water arrives and stalls before digging a drain without an outlet.", "Mark pooling during/after rain and inspect existing outlets; locate buried utilities before work.", "Remove leaves and sediment, inspect access points, and test with a small clean-water flow.", "Repeated clogs need upstream sediment control; persistent pooling/backflow needs a professional grade and capacity check."]),
  鱼缸鱼池: profile("water", ["先完成承重、防跌入、漏水与循环测试，再考虑放入生物。", "空缸池检查接缝后分次加水，标记水位；测试溢流及停泵时回流水位。", "留出清洁过滤和捞取杂物的通道；记录设备状态与异常水位。", "漏水、电器受潮或停泵回流接近溢出时先停用相应设备并处理。"], ["Test support, fall protection, leaks, and circulation before adding animals.", "Inspect joints, fill in stages, mark the level, and test overflow and pump-stop backflow.", "Keep filter-cleaning and debris-removal access and log equipment and unusual levels.", "For leakage, wet electrics, or near-overflow backflow, isolate the affected equipment and resolve the cause."]),
  水循环过滤: profile("water", ["先去除固体杂物，再让生物过滤稳定工作，清洁不等于全部换新。", "按设备说明排布过滤材料，标记正常流量和水位，确认进出水不会短路。", "先清机械拦污层；生物滤材按系统要求维护，避免一次全换并同时大量增鱼。", "流量下降查堵塞与泵；氨或亚硝酸盐异常时暂停增养，检查循环并寻求水族专业建议。"], ["Remove solids first and preserve biological filtration; cleaning is not replacing everything.", "Arrange media as specified, mark normal flow/levels, and check that inlet and outlet do not short-circuit.", "Clean mechanical capture first; maintain biological media for the system and avoid replacing all of it while increasing stock.", "For low flow check clogs/pump; abnormal ammonia or nitrite means stop stocking and seek aquatic advice."]),
  鸡舍: profile("housing", ["睡觉、产蛋、饮水与清粪应各有方便维护的位置。", "设置稳固栖架和安静产蛋处，饮水器避开睡眠区；检查夜间防天敌门锁。", "每日收蛋、移走湿垫料，检查栖架是否松动、舍内是否闷臭。", "氨味明显或脚部总是脏湿时先处理粪便、漏水和通风，不只加香味除臭。"], ["Separate practical roosting, nesting, watering, and manure-cleaning areas.", "Install stable roosts and quiet nests, keep drinkers away from sleeping areas, and check predator-resistant night latches.", "Collect eggs, remove wet bedding, and inspect loose roosts and stale air daily.", "For strong ammonia or persistently dirty wet feet, address manure, leaks, and airflow rather than masking odor."]),
  鸭舍: profile("housing", ["重点把饮水带来的湿区与干燥休息区分开。", "饮水点放在可排水、易清洗的位置，通往休息区的地面防滑。", "每天清理泼出的水和湿垫料，检查出入口及夜间门锁。", "胸腹羽毛长期脏湿时先查卧处和排水；不要靠频繁冲洗动物代替清舍。"], ["Separate the splash-prone drinking area from dry resting space.", "Place drinkers where drainage and cleaning are easy and keep the route to shelter non-slip.", "Clear spills and wet bedding daily and check entrances and night latches.", "For persistently dirty wet breast/belly feathers, inspect bedding and drainage rather than repeatedly washing birds."]),
  兔舍: profile("housing", ["提供干燥、不伤脚的休息面和可躲藏活动的空间。", "检查底面、门缝与可咬到的电线；备干草区、清水和安静躲藏处。", "每天清理厕所和湿垫料，检查足底接触面是否粗糙或潮湿。", "兔子总趴湿处、喘气或不吃时立即查温度与状态，异常及时联系兽医。"], ["Provide dry, foot-friendly resting surfaces plus hiding and activity space.", "Check flooring, door gaps, and reachable wires; prepare hay, water, and a quiet hide.", "Clean litter and wet bedding daily and inspect surfaces for roughness and dampness.", "Lying in wet areas, panting, or not eating needs immediate condition/temperature checks and veterinary advice if abnormal."]),
  围栏: profile("housing", ["按要留住的动物和要挡住的天敌分别查薄弱点。", "沿地面、转角、门扣和搭接处逐段检查，排除能卡头或夹脚的孔隙。", "巡查掘洞、翘边和松动立柱；草木遮住下沿时及时整理检查。", "发现动物尝试钻逃先隔离该段并修复，不能只把它赶回去。"], ["Inspect separately for escape by residents and entry by predators.", "Check ground edges, corners, latches, and joins for head or foot traps.", "Look for digging, lifted edges, and loose posts; clear vegetation obscuring the base.", "If an animal attempts escape, isolate and repair that section rather than merely chasing it back."]),
  堆肥箱: profile("compost", ["让投料、翻拌和取熟料都做得到，而不是只有一个封闭桶。", "选择可清理、通风又不积水的位置，试着用工具伸到箱底；备一处熟化空间。", "投料口和边角盖好干料，检查通气孔有无堵塞和小动物进入。", "底部积液、箱内发臭时先减湿料、疏通并翻松；不把渗出液当作可直接浇叶的肥水。"], ["Allow loading, mixing, and finished-compost access, not just a sealed container.", "Choose a cleanable, ventilated, non-waterlogged site and test tool access to the base; reserve curing space.", "Cover scraps at openings/edges and check ventilation blockage and animal entry.", "For pooled liquid and odor, reduce wet additions, clear and loosen; do not assume leachate is safe foliar fertilizer."]),
};

// The remaining domains are kept in separate maps so identical names in
// different categories cannot accidentally receive the wrong instructions.
const ecologyProfiles: Record<string, Profile> = {
  莫斯: profile("aquaticPlant", ["以附着成形和定期薄剪为主，不把整团厚压在底部。", "拆成薄小片固定在石木表面，检查线头和连接处不妨碍鱼虾。", "剪去过厚部分并吸走夹住的碎屑，保留能继续长出的绿色部分。", "内部发黑或积脏先检查铺得过厚和水流死角。"], ["Grow a thin attached layer and trim instead of packing a thick clump.", "Attach small thin portions to hardscape and check ties do not trap animals.", "Thin dense growth and remove trapped debris while retaining healthy green parts.", "Dark, dirty interiors call for checking excessive thickness and stagnant pockets."]),
  水榕: profile("aquaticPlant", ["水榕适合固定在石木上，粗壮根茎不能埋住。", "把细根与横向根茎分清，只固定根或根茎外侧，保持根茎露出。", "轻擦老叶积尘和附着藻，剪除完全坏死叶片，观察根茎上的新芽。", "根茎发软先查是否被埋、绑得过紧或局部坏死，不继续加肥。"], ["Anubias can attach to hardscape; keep its thick rhizome exposed.", "Distinguish fine roots from the horizontal rhizome and secure it without burial.", "Gently clear debris/algae on older leaves, remove dead leaves, and watch new shoots.", "For a soft rhizome, inspect burial, tight ties, or rot before adding fertilizer."]),
  椒草: profile("aquaticPlant", ["定植后重在保持位置稳定，并观察叶心是否继续长新叶。", "把根种入底床，叶心留在表面；同株旧叶状态先拍照留作对比。", "清除已经软烂的叶片，避免反复拔起检查根系。", "旧叶消融不等于整株死亡；检查叶心和根，再决定是否移除。"], ["Keep Cryptocoryne settled and track new leaves from the crown.", "Plant roots in the substrate with the crown exposed and photograph old leaves.", "Remove fully decayed leaves without repeatedly uprooting the plant.", "Old-leaf melt is not proof of whole-plant death; inspect the crown and roots first."]),
  皇冠草: profile("aquaticPlant", ["按丛生水草预留成株叶片展开的位置。", "单株定植，根扎入底床但不埋叶心，与前景草和出水口留开距离。", "从基部剪除衰老叶，记录新叶大小与周围遮阴变化。", "新叶长期变小先检查根区、遮光和底床变化，不一次叠加多种肥。"], ["Leave room for a rosette plant's mature spread.", "Plant separately with roots below and crown above the substrate, clear of foreground plants and outlets.", "Remove aging leaves at the base and track new-leaf size and shading.", "For persistently smaller new leaves, review root zone, shading, and substrate changes before stacking fertilizers."]),
  矮珍珠: profile("aquaticPlant", ["把铺地草分小丛种稳，比整块厚铺更容易检查成活。", "确认购买的准确品种，分小份留空隙定植，轻轻试查是否扎稳。", "留意空隙是否长出新枝，修剪过厚草毯并捞净剪屑。", "整片浮起先查是否过厚、底部失根或固定不稳，分区补植。"], ["Establish small portions of carpeting plants rather than one thick mat.", "Confirm the exact trade species, plant small spaced portions, and check anchoring gently.", "Watch new growth fill gaps, thin thick mats, and remove cuttings.", "For lifting mats, check excess thickness, root loss, and anchoring; replant in sections."]),
  牛毛毡: profile("aquaticPlant", ["用小丛扩展前景草坪，保留根部之间的生长空间。", "分丛栽入底床，基部不要整团压埋；把种植范围拍下来。", "清理枯叶和缠在草丛里的残饵，观察新匍匐生长是否外扩。", "中间黄、边缘绿时查过密和积污，先疏开再观察。"], ["Plant small hairgrass clumps with room for roots to spread.", "Set divided clumps without burying the entire base and photograph the planted area.", "Remove dead blades and trapped food and track outward runners.", "If centers yellow but edges remain green, check crowding and debris before further changes."]),
  宫廷草: profile("aquaticPlant", ["茎草要分枝种植，修剪后用健康顶芽更新稀疏处。", "除去要埋入底床处的叶片，茎之间留间隙，避免整束插入。", "逐次剪高、补低，保留侧芽，防止上层把下层完全遮住。", "底部掉叶先查遮光和过密，重新分株比不断加高灯强更可控。"], ["Space stems and use healthy tops to renew sparse growth.", "Remove leaves on the buried portion and plant stems with gaps rather than as a bundle.", "Trim tall stems gradually and retain side shoots so the top does not shade the entire base.", "For lower-leaf loss, check shading and crowding before simply increasing light."]),
  绿菊: profile("aquaticPlant", ["细裂叶容易夹碎屑，修剪与水流检查要一起做。", "保留健康茎顶，分根茎定植，让每丛周围能流通水。", "轻轻移除缠叶杂物，剪下健康顶枝补植，捞清断叶。", "下部叶片大量脱落时查光是否被挡及根茎是否被压伤。"], ["Fine divided leaves trap debris; combine pruning with flow checks.", "Keep healthy tops and space stems so water can move between them.", "Gently clear caught debris, replant healthy tops, and collect shed leaves.", "For heavy lower-leaf loss, inspect shading and damaged or compressed stem bases."]),
  红蝴蝶: profile("aquaticPlant", ["先养稳新叶与根，再评估颜色，不为追红同时猛调灯和肥。", "确认准确品种及供应方栽培条件，分茎种植并记录原来叶色。", "固定拍摄位置比较新叶，灯、肥或碳源每次只改一项。", "叶尖损伤或大量落叶时先回查最近改动，不把颜色浅直接判为缺肥。"], ["Establish roots and new leaves before chasing red coloration.", "Confirm the exact species and supplier conditions, space stems, and record initial color.", "Compare new leaves from a fixed photo position and change only light, nutrients, or carbon at a time.", "For damaged tips or heavy leaf loss, review recent changes; pale color alone is not a fertilizer diagnosis."]),
  宝塔草: profile("aquaticPlant", ["分层叶片容易互相遮挡，株间留隙更方便保持形态。", "分茎定植，避免压碎层状叶片，给上部长高留空间。", "从健康节位分次修剪，及时捞出漂浮剪屑，比较下层叶片状态。", "下层发黑或大量掉叶时查过密、积污和遮光。"], ["Leave room around layered foliage so lower leaves are not crowded out.", "Plant stems separately without crushing whorls and leave vertical space.", "Trim healthy sections gradually, collect floating debris, and compare lower foliage.", "For dark or shedding lower leaves, inspect density, debris, and shading."]),
  蜈蚣草: profile("aquaticPlant", ["商品俗名并不唯一，先凭标签确定是哪种茎草。", "保留标签与全株照片，按确认后的水生品种分茎定植。", "查看新芽与节间变化，修剪时保留健康茎段并移走坏死部分。", "长期只有旧叶没有水下新生长，先核对是否买到适合长期沉水的种类。"], ["The trade name is ambiguous; identify the actual stem plant first.", "Keep the label and whole-plant photo, then space stems for the confirmed aquatic species.", "Track shoots and internodes; retain healthy sections and remove dead material during pruning.", "If old leaves persist without submerged new growth, verify suitability for long-term underwater growth."]),
  金鱼藻: profile("aquaticPlant", ["可先漂浮观察，避免把脆弱茎段深压进底床。", "将健康茎段放在可获得光的位置，避免堵住进水口。", "控制漂浮量，给下层草留光，捞去断落细叶。", "大量掉叶时回查水体、光照和运输后的变化，先清掉残叶防积污。"], ["Start with floating growth rather than crushing delicate stems deep into substrate.", "Place healthy stems in light without blocking intakes.", "Control floating cover to leave light below and remove shed fine leaves.", "For heavy shedding, review water, light, and transport changes and clear debris first."]),
  狐尾藻: profile("aquaticPlant", ["先确认具体狐尾藻，再选择沉水或挺水的管理方式。", "按来源标签确认物种与生长形态，分茎安置，不让枝叶堵住设备。", "及时修剪伸出计划范围的枝条，剪屑集中清理而不随排水流走。", "下部稀疏先查上层遮阴；不将水族种植株移入自然池塘。"], ["Identify the particular water-milfoil before choosing submerged or emergent care.", "Use the source label to confirm species and growth form; keep separated stems clear of equipment.", "Trim growth beyond the intended area and collect cuttings instead of flushing them away.", "For sparse bases, check upper shading; do not transfer aquarium plants to natural ponds."]),
  浮萍: profile("aquaticPlant", ["管理重点是表面覆盖率，而不是让整片水面长期封住。", "先放少量在安静水面，给进出水口和其他植物上方留空。", "定期捞去多余部分，查看下层光线、水面交换和设备堵塞。", "快速铺满时先疏除并回查营养来源；发黄则检查水流冲击和环境变化。"], ["Manage surface coverage rather than leaving the whole surface sealed.", "Start with a small amount on calm water, clear of outlets and plants below.", "Remove excess regularly and check light below, surface exchange, and equipment blockage.", "For rapid coverage thin first and review nutrient inputs; for yellowing inspect turbulence and changes."]),
  金鱼: profile("fish", ["用能容纳成鱼的过滤水体饲养，不把小圆缸当长期空间。", "先核对品种成年体型和现有水体，准备宽敞游动区与安全装饰。", "按实际摄食分次少量投喂，清走残饵，观察排泄和游姿。", "浮头、侧游或突然夹鳍时立即测水并检查增氧，不先按外观猜病用药。"], ["Use a filtered system sized for adult goldfish, not a bowl as a permanent home.", "Check adult size and system capacity and provide swimming space and safe decor.", "Offer small portions based on intake, remove leftovers, and observe waste and swimming.", "For gasping, sideways swimming, or clamped fins, test water and aeration before guessing a disease."]),
  锦鲤: profile("fish", ["锦鲤的长期照护以池体容量、过滤和日常巡池为基础。", "核对成鱼体型、池深与安全围护，先测试循环、排污和断电预案。", "投喂时逐条看体表和摄食，高温及闷热天气重点查看呼吸。", "集体浮头或集中进水口时先查氧气和设备，暂停继续投饵并及时求助。"], ["Long-term koi care depends on pond capacity, filtration, and routine checks.", "Review adult size, depth, guarding, circulation, waste removal, and power-loss plans.", "Inspect each fish while feeding and pay extra attention to breathing in hot, still weather.", "For group gasping or clustering at the inlet, check oxygen and equipment, pause feeding, and seek prompt help."]),
  孔雀鱼: profile("fish", ["在稳定水体中管理群体与繁殖数量，避免越养越挤。", "入缸前确定现有数量和后续安置，确认雄雌组合及同伴兼容性。", "观察追逐和弱鱼是否能吃到，统计幼鱼出现后重新评估负荷。", "鱼鳍受损或持续躲角落时先排查追咬、拥挤与水质。"], ["Manage population and breeding in a stable aquarium to avoid crowding.", "Plan stocking and future homes and check sex mix and companion compatibility.", "Watch chasing and feeding access; review system load when fry appear.", "For damaged fins or persistent hiding, inspect aggression, crowding, and water."]),
  斗鱼: profile("fish", ["提供有过滤、合适水温与休息点的环境，不以小杯长期饲养。", "雄鱼不直接同缸，检查装饰无锐边，留水面呼吸通道和防跳盖。", "观察食欲和鳍缘，调整过强直冲水流，给安静休息的位置。", "长期夹鳍或躲避先查水温、水质和水流；不反复照镜刺激。"], ["Provide suitable temperature, filtration, and resting places, not permanent cup housing.", "Do not house males together; remove sharp decor and retain surface access and a jump-resistant lid.", "Observe appetite and fin edges, reduce excessive direct flow, and provide quiet rests.", "For persistent clamping or hiding, check temperature, water, and flow rather than repeated mirror stimulation."]),
  红绿灯鱼: profile("fish", ["以适合的群体、稳定水质和可躲藏植物减轻紧张。", "先确认群养与同伴需求，留游动区并用水草提供遮蔽。", "观察群体是否正常活动和所有个体是否摄食，不只盯着最活跃的鱼。", "持续离群、褪色或呼吸急促时测水并查看是否被追逐。"], ["Support suitable group living, stable water, and planted shelter.", "Confirm shoaling and companion needs and combine swimming room with plant cover.", "Check activity and feeding across the group, not only the most active fish.", "For persistent isolation, fading, or rapid breathing, test water and inspect harassment."]),
  原生鱼: profile("fish", ["“原生鱼”不是单一物种，先辨种再决定水温、流速和食物。", "保存准确种名与合法来源信息，分别确认成鱼体型、温度和流速需求。", "用温度计与水流观察记录季节变化，食物按已确认的食性选择。", "未知种拒食不要轮番投药或野采饵料；先请可靠人员辨种并核对环境。"], ["Native fish are not one species; identify before choosing temperature, flow, or diet.", "Keep the exact name and lawful source and confirm adult size, temperature, and flow separately.", "Log seasonal temperature/flow and choose food for the confirmed diet.", "For an unidentified fish refusing food, seek identification and environment review rather than cycling drugs or wild foods."]),
  海水鱼: profile("marine", ["先确定鱼的种类及是否珊瑚缸，再安排设备与同伴。", "购买前核对成年体型、食性、领域性和跳缸风险，预留隔离观察条件。", "逐条确认摄食，不把无脊椎动物全部视为安全同伴；及时检查争斗。", "盐度突变或多鱼同时异常时先复核检测与补水操作，停止新增生物。"], ["Choose species and fish-only versus reef setup before equipment and companions.", "Check adult size, diet, territorial behavior, and jumping risk and plan separate observation.", "Confirm each fish feeds and do not assume all invertebrates are compatible; inspect aggression.", "For salinity changes or several affected fish, verify tests/top-ups and stop adding livestock."]),
  米虾: profile("invertebrate", ["重视水体稳定、躲藏与少量投喂，不只把它当清藻工具。", "确认具体虾种，准备遮蔽物并保护过滤进水口，避免幼虾卷入。", "用投喂点观察残饵与活动，蜕壳后减少翻动躲藏物。", "多只同时乱游或不动时先查水质、近期换水与添加物，不先补不明矿物。"], ["Prioritize stable water, cover, and measured feeding, not just algae cleaning.", "Identify the shrimp and protect filter intakes so juveniles are not drawn in.", "Use a feeding spot to monitor leftovers and avoid moving hides after molts.", "For several erratic or inactive shrimp, check water, recent changes, and additives before adding minerals."]),
  水晶虾: profile("invertebrate", ["先核对具体品系的水质需求，稳定比频繁纠偏更重要。", "记录来源水条件，准备匹配的饲养水与检测工具，谨慎安排适应过程。", "记录每次补水和换水，观察蜕壳及抱卵，不同时更换底床和滤材。", "接连蜕壳失败或死亡时先停新增，核对变化记录并请专业人员判断。"], ["Confirm the strain's water needs and prioritize stability over repeated corrections.", "Record source-water conditions and prepare matching water, tests, and an appropriate acclimation plan.", "Log top-ups/changes and observe molts and eggs; avoid changing substrate and filter media together.", "For repeated molt failures or deaths, stop additions, review changes, and seek specialist advice."]),
  螯虾: profile("invertebrate", ["提前安排防逃和蜕壳避让，不默认能与鱼虾混养。", "核对成年大小，盖好可攀出的管线缝，准备各自可退入的躲藏处。", "投喂后查看是否互相争抢，蜕壳时减少干扰并观察同伴接近。", "伤肢或反复追咬时先分开风险个体并调整空间，不靠多投食解决一切。"], ["Plan escape protection and molt refuges; do not assume fish/shrimp compatibility.", "Confirm adult size, secure gaps around climbable pipes, and provide separate refuges.", "Check food competition and limit disturbance around molts and approaching companions.", "For injuries or repeated attacks, separate at-risk animals and review space rather than just feeding more."]),
  螃蟹: profile("invertebrate", ["先确定是淡水、汽水还是海水蟹，以及需要多少陆地。", "向来源方核对准确物种；需要陆栖区的，先测试能轻松出水和防逃逸。", "从外部观察上岸、进食与蜕壳，清走陆区残饵，保持必要通风。", "不断攀爬或持续泡在不合适区域时先复核水陆设置，不能按所有蟹通用参数处理。"], ["Identify freshwater, brackish, or marine needs and the required land area.", "Confirm the species; where land is needed, test easy water exits and escape protection.", "Observe land use, feeding, and molts; remove land-area leftovers and retain ventilation.", "For persistent climbing or unsuitable water/land use, review habitat rather than using universal crab settings."]),
  蜗牛: profile("landSnail", ["以观察爬行、取食和壳体状态为主，避免干晒和粗暴揭取。", "留阴湿躲藏与通风区，食物来源无农药；不强拉黏附在表面的个体。", "换走腐败食物，检查壳口和活动，固定角度记录壳体变化。", "壳受伤或长时间缩闭时先查外伤、干燥与环境改变，不随意盐洗。"], ["Observe movement, feeding, and shell condition without sun-drying or forced removal.", "Provide shaded moist cover and ventilation; use pesticide-free food and do not pull attached animals.", "Replace spoiled food, inspect the shell opening/activity, and repeat shell photos.", "For shell damage or prolonged withdrawal, inspect injury, dryness, and changes; never salt-wash."]),
  蛞蝓: profile("landSnail", ["无壳体保护，更适合在原处观察夜间活动与湿度关系。", "选择落叶或木片附近固定观察点，不为了拍照移到干热地面。", "记录雨后与干燥时的活动和取食痕，保留其躲藏处。", "发现贴近幼苗的啃食时先确认对象，可用隔离和移走躲藏杂物保护苗，不直接撒盐。"], ["With no shell protection, observe slug activity and moisture in place.", "Use a fixed spot near leaf litter or wood and avoid moving slugs onto hot dry surfaces.", "Log activity and feeding traces in wet/dry weather and retain shelter.", "For seedling damage, verify the cause and protect plants with barriers or shelter management, not salt."]),
  田螺: profile("invertebrate", ["先辨明具体螺类，检查底部摄食和水体清洁。", "确认淡水适应与食性，底面留可观察区域，避免只见壳不见活动。", "查看足部活动、摄食和剩食，发现死亡个体及时确认并移除。", "连续上爬或闭壳不动时检测水质，不能只按吃藻不足来加饵。"], ["Identify the snail and observe feeding at the bottom and water condition.", "Confirm freshwater and dietary needs and retain a visible bottom area.", "Check foot movement, feeding, and leftovers; confirm and remove deaths promptly.", "Persistent climbing or closure warrants water tests rather than simply adding food."]),
  苹果螺: profile("invertebrate", ["俗名可能混指不同螺类，先确定种类再判断繁殖与植物兼容性。", "核对来源照片和学名，检查会不会啃食栽培水草并安排数量上限。", "记录新增小螺和卵，调整过量残饵而不是让数量无计划增加。", "壳面异常、反复逃离或数量暴增时分别排查水质、识别与投喂。"], ["The trade name can cover different snails; identify before planning breeding or plants.", "Check source photos/name, possible plant feeding, and a population plan.", "Log eggs and juveniles and correct excessive leftovers rather than allowing uncontrolled growth.", "For shell changes, repeated escape, or a population boom, review water, identification, and feeding separately."]),
  角螺: profile("invertebrate", ["重点观察附着、刮食和壳体，进缸前确认实际食物来源。", "在已稳定的水族系统中安排可刮食表面，确认物种和防逃缝隙。", "查看同一时段位置是否变化，检查壳口、玻璃和石面摄食痕。", "久不移动时先判断是否休息并测水，不频繁翻弄或持续往缸里加药。"], ["Observe attachment, grazing, and shell condition and plan a real food supply.", "Use an established system with grazing surfaces and check species and escape gaps.", "Compare position at consistent times and inspect the shell opening and grazing tracks.", "For long inactivity, consider rest and test water instead of repeated handling or medication."]),
  洋葱螺: profile("invertebrate", ["保留可刮食的表面，但不要以长藻代替整体水质管理。", "确认准确品种，在稳定水体中安置，避免与会咬螺的同伴混养。", "清洁时保留部分适合刮食的表面，记录活动和壳体变化。", "频繁爬出或附着乏力时先查水质与添加剂记录。"], ["Retain grazing surfaces without using algae as a substitute for water management.", "Identify the species and avoid companions that bite snails.", "Retain some suitable grazing surfaces during cleaning and track activity/shell condition.", "For repeated exits or weak attachment, check water and additive history first."]),
  河蚌: profile("invertebrate", ["河蚌是需要合适食物的滤食动物，不是免维护净水器。", "购买前确认物种、成熟水体与食物供应，留能检查的位置，不深埋到无法观察。", "轻度观察开闭壳和周边沉积，按物种要求管理食物与水流。", "长期张壳无反应或异味需及时检查处理，不能等待它自行把脏水过滤好。"], ["Freshwater mussels need suitable food; they are not maintenance-free filters.", "Confirm species, established conditions, and food supply before purchase and retain inspection access.", "Observe opening/closing and deposits without repeated disturbance; manage species-appropriate food and flow.", "Persistent unresponsive gaping or odor needs prompt assessment, not waiting for the animal to clean dirty water."]),
  蛤蜊: profile("invertebrate", ["食用名称不代表适合家庭水族，先确认盐度与滤食条件。", "确认是海水或汽水种及食物来源，没有匹配系统就不要临时放进淡水缸。", "记录盐度、底床和开闭壳变化，按实际种类维持水流与饲料。", "长期闭壳或无反应先核对水体条件；饲养过的水族个体不作为食材。"], ["An edible trade name does not establish aquarium suitability; confirm salinity and food.", "Check marine/brackish identity and food; do not temporarily place unmatched animals in freshwater.", "Log salinity, substrate, and shell behavior and maintain species-specific flow and food.", "For prolonged closure or no response, check conditions first; do not eat aquarium-kept animals."]),
  海螺: profile("marine", ["先分清草食、杂食或捕食种，不能都当除藻螺。", "核对准确种名和食性，确认不会捕食现有鱼虾或珊瑚。", "观察实际摄食和夜间位置，检查是否卡在石缝或被同伴攻击。", "翻倒、长期不动或壳口损伤时先排查卡住、攻击与水质，勿徒手处理未知有毒种。"], ["Identify herbivorous, omnivorous, or predatory snails rather than treating all as grazers.", "Confirm the species/diet and compatibility with current fish, shrimp, and corals.", "Check feeding and nighttime position for trapping in rockwork or attacks.", "For overturning, inactivity, or opening injuries, inspect trapping, aggression, and water; do not handle unknown venomous species."]),
  青蛙: profile("amphibian", ["从蝌蚪到成蛙需求不同，观察阶段变化比固定天数更重要。", "确认是水栖或半水栖种，转为陆栖的阶段提前准备容易爬出的缓坡。", "查看能否正常上岸、皮肤和取食，水陆区域分别清理。", "开始长肢或尾部缩短时重新核对出水条件，不让幼体困在深水中。"], ["Tadpoles and adults differ; follow the actual life stage, not a fixed day count.", "Identify aquatic or semi-aquatic needs and prepare easy exits before a land-going stage.", "Check water exits, skin, and feeding and clean land/water areas separately.", "When limbs develop or the tail shortens, review exit access so transitioning animals are not trapped."]),
  树蛙: profile("amphibian", ["树栖种需要稳定攀附与通风，不能只给一盆水。", "确认物种后安装稳固枝叶、躲藏和合适浅水区，盖好通风防逃网。", "观察能否稳稳攀附，清理叶面残饵，检查喷湿后是否持续闷湿。", "频繁滑落、腹部异常或皮肤损伤先检查表面和环境，并咨询异宠兽医。"], ["Arboreal frogs need secure climbing and airflow, not just a bowl of water.", "After identification, provide stable branches, cover, an appropriate shallow water area, and a ventilated secure lid.", "Observe grip, clear leftovers, and check that misting does not leave persistent stagnant wetness.", "Repeated slipping or skin/body abnormalities need surface/environment checks and exotics-vet advice."]),
  蟾蜍: profile("amphibian", ["以地面躲藏、适当湿度与清洁出水条件为重点。", "先辨种，准备可躲藏地面和易进出的水区，避免粗糙锐利材料。", "从外部观察皮肤和活动，清除残饵并检查基质是否积水。", "不断泡水、异常消瘦或皮肤变化时核对环境，不把所有分泌物都当病变处理。"], ["Focus on terrestrial shelter, suitable moisture, and safe water access.", "Identify the species and provide ground hides and easy water entry/exit without sharp materials.", "Observe skin/activity externally and remove leftovers and waterlogged substrate.", "Persistent soaking, weight loss, or skin changes need environment review; not every secretion indicates disease."]),
  蝾螈: profile("amphibian", ["不同蝾螈的水陆需求差异很大，不能照搬热带鱼缸。", "确认准确种名和生活阶段，再定水深、陆地、温度及防逃结构。", "检查进出水、皮肤和剩食，设备吸入口需避免卷入个体。", "异常漂浮、皮肤损伤或逃离水区时先复核物种要求与水质。"], ["Salamanders differ greatly in water/land needs; a tropical-fish setup is not universal.", "Identify species and life stage before choosing depth, land, temperature, and escape protection.", "Inspect water access, skin, and leftovers and guard equipment intakes.", "For abnormal floating, skin damage, or avoidance of water, review species requirements and water quality."]),
  龟: profile("reptile", ["先分清水龟、半水龟或陆龟；三者不能共用一套温度、水深和食谱。", "水龟准备能完全离水的干燥晒背处和安全出水坡；陆龟则先核对陆地基质、躲藏和活动区。", "按已确认物种安排UVB与温度梯度；逐项检查晒背、进食、排泄和壳体照片。", "歪浮、张口呼吸、眼肿或壳体软烂时及时就医，不用统一盐浴或晒太阳代替治疗。"], ["Identify aquatic, semi-aquatic, or terrestrial turtles/tortoises; depth, diet, and temperatures differ.", "For aquatic turtles provide a fully dry basking site and safe exit; for tortoises review terrestrial substrate, shelter, and space.", "Set UVB and temperature gradients for the identified species and track basking, food, droppings, and shell photos.", "Abnormal floating, open-mouth breathing, swollen eyes, or shell decay needs veterinary care, not a universal salt bath or sun remedy."]),
  蛇: profile("reptile", ["先确认物种、成年体型和安全等级，再考虑长期饲养。", "只考虑能可靠识别且有合法来源的种类；检查锁扣、管线孔与冷热两端躲藏。", "按种类制定喂食与测重记录，蜕皮期间观察完整性，不强行揭皮。", "持续残皮、呼吸杂音或体重下降应找异宠兽医；不要用活体猎物无人看管试喂。"], ["Identify species, adult size, and safety requirements before keeping a snake.", "Consider only reliably identified, lawfully sourced species; inspect locks, cable gaps, and hides across the gradient.", "Follow a species-specific feeding/weight log and observe sheds without forcibly peeling skin.", "Persistent retained shed, breathing noise, or weight loss needs an exotics vet; never leave live prey unattended."]),
  蜥蜴: profile("reptile", ["树栖、地栖、植食和虫食种差异大，先用准确种名建立照护记录。", "按物种安排攀爬或地面空间，确认晒点、躲藏和食谱，不用单一虫料通喂。", "核对设备实际运行，观察抓握、步态、尾部和粪便，定期留体重记录。", "无力、跛行、持续闭眼或拒食时检查条件并就医，不自行猛补维生素。"], ["Arboreal, terrestrial, plant-eating, and insect-eating lizards need species-specific care.", "Provide suitable climbing/ground space, basking, hides, and diet rather than feeding every species one insect food.", "Verify equipment and observe grip, gait, tail, and droppings with periodic weight records.", "Weakness, limping, persistently closed eyes, or refusal to eat needs checks and veterinary advice, not vitamin megadoses."]),
  蝴蝶: profile("insect", ["种植寄主与蜜源、少干扰，比捕捉成蝶更适合庭院观察。", "确认本地蝶种的幼虫寄主，保留可供停歇和化蛹的安静枝叶。", "记录访花、产卵和幼虫变化，避免对寄主喷施杀虫剂。", "叶片被吃时先确认是否为目标蝶种幼虫，不因孔洞立即清除。"], ["Host and nectar plants with low disturbance support observation better than catching adults.", "Identify host plants for local larvae and retain quiet foliage for resting and pupation.", "Log flower visits, egg laying, and larvae and avoid insecticides on host plants.", "Identify caterpillars before removing them simply because host leaves have holes."]),
  蛾: profile("insect", ["多在夜间活动，可用固定位置观察，不长时间强光追照。", "记录发现植物和停栖位置，先拍翅形与姿态辨种。", "保留幼虫寄主和安静角落，夜间用短时低干扰观察记录。", "室内大量出现时先核对是否储粮害虫，别把室内治理和庭院观察混为一谈。"], ["Observe moths from a fixed spot without prolonged bright-light pursuit.", "Record the plant and resting site and photograph wing shape and posture for identification.", "Retain host plants and quiet corners and use brief, low-disturbance nighttime checks.", "Many indoors warrant checking stored-food pests; indoor control and garden observation are different tasks."]),
  毛毛虫: profile("insect", ["先认虫与寄主；幼虫并不能随便换一把菜叶喂。", "拍下头部、体侧与原取食植物，在确认寄主前不要更换食物。", "若合法观察饲养，保持通风，换新鲜寄主叶并清理粪便，不拥挤。", "停食并固定身体可能接近化蛹，先观察，不拉扯、不催食；不触碰未知毛刺种。"], ["Identify the caterpillar and host; arbitrary leaves are not a substitute.", "Photograph head, side, and original food plant before changing food.", "For lawful captive observation, ventilate, refresh confirmed host leaves, remove waste, and avoid crowding.", "Stopping feeding and anchoring may precede pupation; observe rather than pull or force-feed, and do not handle unknown hairy species."]),
  蜜蜂: profile("insect", ["庭院首先提供连续花源与低干扰环境；蜂群管理需要专门经验。", "从远处确认蜜蜂还是其他蜂类，避开巢口和飞行通道。", "记录访花时间、植物与数量，开花期避免在访花植物上喷杀虫剂。", "发现蜂群聚集或筑巢影响通行，隔离人宠并联系有经验人员，不自行封巢或点火。"], ["Support flowers and low disturbance; colony management requires trained experience.", "Identify bees from a distance and stay out of nest entrances and flight paths.", "Log flower visits, plants, and numbers and avoid insecticides on visited blooms.", "For swarms/nests obstructing access, keep people and pets clear and contact experienced help; do not seal or burn nests."]),
  甲虫: profile("insect", ["甲虫与幼虫食性可能不同，先确认种类和阶段。", "记录发现的植物、木材或土壤，辨种后再决定寄主、基质和空间。", "观察取食与钻藏，保留适合的原观察环境，不频繁挖开幼虫。", "蛀孔或叶片损伤先拍照辨别对象，不能看见甲虫就一概喷药。"], ["Adult beetles and larvae may have different diets; identify species and stage.", "Record the plant, wood, or soil and confirm host, substrate, and space after identification.", "Observe feeding and hiding without repeatedly excavating larvae.", "Photograph and identify holes or leaf damage before treating all beetles as pests."]),
  螳螂: profile("insect", ["留意独居与蜕皮空间，不把多只挤在同一小盒。", "辨种后准备稳固攀附和充足悬挂空间，使用防逃通风盖。", "看是否正常捕食和攀附，蜕皮前后减少喂食干扰并清走危险残留猎物。", "蜕皮时掉落或受伤不要强拉残皮，保持安静并寻求有经验者帮助。"], ["Plan individual space and molting clearance instead of crowding a small box.", "After identification, provide stable climbing, hanging clearance, and a ventilated secure lid.", "Check hunting and grip, minimize disturbance near molts, and remove leftover prey that could injure it.", "After a fall or molt injury, do not pull retained skin; keep it quiet and seek experienced advice."]),
  蝗虫: profile("insect", ["以辨种、寄主与数量变化记录为主，避免无计划繁殖逃逸。", "在原处记录叶片啃食与个体，若观察饲养须确认合法来源和严密防逃。", "检查食物是否新鲜、容器是否拥挤，定期清理粪便。", "出现集中啃食先记录范围并辨种，再考虑防护，不把观察个体带往异地释放。"], ["Track identity, host, and population without uncontrolled breeding or escapes.", "Record feeding in place; captive observation needs lawful sourcing and secure containment.", "Check food freshness and crowding and clear droppings regularly.", "Map concentrated feeding and identify before protection measures; never transport specimens for release elsewhere."]),
  蚂蚁: profile("insect", ["观察觅食路线和植物关系，避免随意挖巢或捕捉蚁后。", "在安全距离记录进出点和搬运食物，不堵住巢口做试验。", "比较天气、时间与觅食量；室内食物密封并清除洒落残渣。", "若有叮咬风险或疑似入侵种，停止接触并请专业人员辨识处理。"], ["Observe trails and plant relationships without digging nests or taking queens.", "Record entrances and carried food at a safe distance; do not block nests as an experiment.", "Compare activity with weather/time and seal indoor food and spills.", "For biting risk or suspected invasive species, stop contact and request professional identification."]),
  蝉: profile("insect", ["适合记录羽化与鸣叫，不适合按短周期盒养催生。", "观察树干与附近地面，保留羽化时可攀附的垂直表面。", "发现羽化中的个体不移动，远距离拍摄并记录天气和时间。", "翅未展开时避免碰触；不通过剥壳或拉翅帮助羽化。"], ["Record emergence and calls instead of trying to force a short box-rearing cycle.", "Observe trunks and nearby ground and retain vertical emergence surfaces.", "Do not move emerging individuals; photograph from a distance and log weather/time.", "Avoid touching unexpanded wings and never peel cases or pull wings to assist emergence."]),
  蜻蜓: profile("insect", ["幼体在水中、成体在空中，池边挺水植物是关键观察点。", "在安全池边保留出水茎秆，观察时不要挖捞或跨池搬运幼虫。", "检查羽化壳与成体停栖，清池前先查看植株上是否有正在羽化个体。", "羽化时掉落或被干扰不要反复抓取；保持安静并保留可攀附位置。"], ["Aquatic larvae and flying adults make emergent stems useful observation points.", "Retain stems at a safe pond edge; do not dig up larvae or move them between ponds.", "Look for cases and resting adults and inspect stems before pond maintenance.", "Avoid repeated handling after disturbance during emergence; retain quiet climbing surfaces."]),
  面包虫: profile("insect", ["把幼虫、蛹和成虫阶段分清，控制潮湿与霉变。", "使用来源明确的饲养个体和合适干燥基料，准备通风防逃容器。", "少量供应所需湿料，及时撤去发霉或变质部分，记录各阶段数量。", "大量黑死或螨虫出现先停止扩大饲养，隔离问题容器并检查湿度与食物。"], ["Separate larvae, pupae, and adults in your records and control dampness and mold.", "Use traceable stock, appropriate dry medium, and a ventilated secure container.", "Provide needed moist food sparingly, remove spoilage, and count life stages.", "For mass darkening/deaths or mites, stop expansion, isolate the problem container, and inspect moisture and food."]),
  黑水虻: profile("insect", ["重点管理来源清楚的湿料、透气和幼虫迁出，避免变成积液臭桶。", "准备可排液、防逃且便于清理的容器，少量投放可追溯原料。", "按实际消耗补料，不让新料压成厚层；检查积液、气味和幼虫活力。", "腐臭或大量死亡先停投料并排查积液与过热；不把不明原料养出的虫直接作饲料。"], ["Manage traceable feed, air, and larval movement without creating a foul liquid-filled bin.", "Use a drainable, cleanable, contained vessel and start with small traceable feed additions.", "Replenish according to consumption, avoid compact thick layers, and inspect liquid, odor, and activity.", "For foul odor or deaths, stop feeding and inspect pooling/heat; do not use larvae raised on unknown waste as feed."]),
  蚯蚓: profile("insect", ["先分清土栖观察与堆肥蚯蚓，不把所有蚯蚓放进同一个厨余桶。", "确认用于堆肥的种类，准备疏松湿润垫料和遮阴通风位置。", "少量分区投食，查看旧料消耗与湿度，避免翻动过度或让垫料积水。", "大量向外爬先查过热、积水和过量投料，暂停加料再调整。"], ["Distinguish soil observation from composting species rather than using any worm in a scraps bin.", "Confirm composting species and prepare loose moist bedding in a shaded ventilated site.", "Feed small zones based on previous consumption; avoid overhandling and waterlogging.", "For mass escape, check heat, flooding, and overfeeding and pause additions before adjustment."]),
  蜘蛛: profile("insect", ["多数庭院蜘蛛适合原处观察网、躲藏和捕食，不需要搬入盒中。", "拍下体形、网形和栖息点，在可靠辨种前不徒手触碰。", "避开网和卵囊，记录网的位置与捕食，清扫前先看是否能留一个安静角落。", "进入室内且无法辨认时隔离人宠，请有经验者处理，别冒险手抓。"], ["Observe garden spiders' webs and hunting in place rather than boxing them.", "Photograph body, web, and site and do not handle before reliable identification.", "Avoid webs and egg sacs and consider retaining a quiet corner before cleaning.", "For unidentified indoor spiders, keep people/pets clear and seek experienced help instead of grabbing."]),
  螨: profile("insect", ["螨既有害螨也有捕食螨，先识别损伤和对象，不能一律清除。", "用放大镜检查叶背、网丝和斑点，拍照并记录受影响植物。", "有疑似受害盆栽先分开放，检查新梢与邻盆，工具使用后清洁。", "扩散或辨识不清时请专业人员确认；不自行混配杀螨剂或把用于动物的药喷植物。"], ["Mites include pests and predators; identify damage and the organism before acting.", "Use magnification on leaf undersides, webbing, and speckles and record affected plants.", "Separate suspect potted plants, inspect new growth/neighbors, and clean tools after use.", "For spread or uncertainty, seek identification; do not mix miticides or apply animal medicines to plants."]),
  鹦鹉: profile("petBird", ["以合适食物、可活动空间和每日互动为主，不只靠一碗种子和笼子。", "核对品种食谱，准备安全栖架、可啃咬玩具和防逃活动区域。", "轮换安全玩具，记录实际采食与体重，不突然撤走熟悉食物逼换粮。", "啄羽、持续尖叫或食欲下降时先排查环境与健康，再寻求鸟类兽医或行为指导。"], ["Provide suitable diet, activity, and daily interaction, not just seeds and a cage.", "Confirm the species diet and prepare safe perches, chew items, and escape-proof activity space.", "Rotate safe enrichment and track intake/weight; do not force diet changes by abruptly removing familiar food.", "For feather damage, persistent screaming, or reduced appetite, review health/environment and seek avian or behavioral advice."]),
  鸽子: profile("petBird", ["饲养鸽与野外观察分开，重点保证饮水、通风和稳定休息位置。", "饲养需确认来源，准备易清洗饮水器、稳定栖位和独立观察区。", "清理粪便，观察每只是否采食与行走正常，不让弱鸟长期抢不到食。", "歪头、站立不稳或呼吸异常及时联系鸟类兽医，不自行把多种药混入饮水。"], ["Separate kept pigeons from wildlife observation and prioritize water, airflow, and stable roosts.", "Confirm lawful sourcing and provide cleanable drinkers, stable perches, and separate observation space.", "Clear droppings and check each bird's feeding/gait and access for weaker birds.", "Head tilt, imbalance, or abnormal breathing needs avian-vet advice, not multiple drugs mixed into water."]),
  麻雀: profile("wildlife", ["以观察群体取食、洗浴和季节变化为主，不捉幼鸟饲养。", "选择远离猫狗干扰的观察点，保留安全草籽和灌丛环境。", "记录群体数量与停留时段，若提供水盆则经常清洁并保持浅水。", "看到刚离巢幼鸟先远距离观察亲鸟，不立即带走。"], ["Observe flock feeding, bathing, and seasons rather than taking young sparrows.", "Choose a spot away from pets and retain safe seed-bearing plants and shrubs.", "Log flock size and timing; if providing water, keep it shallow and clean.", "For a fledgling, watch for parents from a distance before assuming it needs removal."]),
  燕子: profile("wildlife", ["保护飞行通道和巢周边安静，观察筑巢与育雏即可。", "从不挡出入口的位置观察，不改动使用中的巢或巢下结构。", "用固定距离记录进出频次，清理环境时避开繁殖活动。", "幼鸟落地或巢损坏时先联系救助人员，不用米饭、牛奶强喂。"], ["Keep flight paths and nests undisturbed and observe nesting/rearing.", "Observe without blocking entrances or altering occupied nests or supporting structures.", "Record visits from a fixed distance and avoid disturbing breeding during cleaning.", "For fallen chicks or damaged nests, contact rehabilitation help rather than force-feeding rice or milk."]),
  斑鸠: profile("wildlife", ["在原地观察停栖、饮水和育雏，尽量少改变巢附近环境。", "选择遮蔽观察位置，留开地面取食区与巢的通道。", "记录配对与往返行为，控制宠物接近，避免频繁走到巢边。", "亲鸟短时离巢并不证明弃巢，先拉开距离观察。"], ["Observe perching, water use, and rearing in place with minimal nest-area changes.", "Use a screened observation position and keep ground-feeding and nest routes clear.", "Log pairing and visits while keeping pets away and avoiding repeated nest approaches.", "A short parental absence is not proof of abandonment; back away and observe."]),
  白头鹎: profile("wildlife", ["可观察访果、访花和鸣叫，优先通过植物提供自然环境。", "记录常来的灌木与果实，不设黏网或用食物诱入室内。", "比较结果季和非结果季活动，修剪灌丛前查看是否有巢。", "果树受啄时用安全隔离保护果实，避免松散网线缠鸟。"], ["Observe fruit/flower visits and calls and support habitat through plants.", "Record favored shrubs/fruit without sticky traps or luring birds indoors.", "Compare activity across fruiting seasons and check shrubs before pruning.", "Protect fruit with safe barriers that cannot entangle birds, not loose net strands."]),
  乌鸫: profile("wildlife", ["落叶层和灌丛是观察翻找食物、停栖的重要位置。", "保留一处少打扰的落叶角落，从固定距离观察。", "记录翻叶取食与洗浴，清洁水盆，减少地面施药。", "看到幼鸟藏在灌丛下先把宠物带离，再观察亲鸟是否回来。"], ["Leaf litter and shrubs offer useful feeding and resting observations.", "Retain a quiet leaf-litter corner and observe from a fixed distance.", "Log leaf-turning and bathing, clean water dishes, and reduce ground pesticide use.", "For a young bird under shrubs, remove pets and watch for returning parents first."]),
  喜鹊: profile("wildlife", ["观察筑巢、搬运和领地活动，避免用长期投喂改变行为。", "远距离确认巢树和飞行路线，不攀树查看或搬动巢材。", "记录巢周活动及季节变化，收好散落塑料绳和危险线材。", "育雏期护巢时绕行，不驱赶或逗弄，必要时请专业人员协助。"], ["Observe nests, carrying, and territory without persistent feeding that changes behavior.", "Identify nest trees/routes from a distance without climbing or moving nest material.", "Log seasonal activity and remove loose plastic strings and dangerous lines from the surroundings.", "Give defending parents space and seek professional help if needed rather than provoking them."]),
  鹭: profile("wildlife", ["池塘周边观察涉水捕食，注意人与鸟都能安全离开。", "在岸上固定点观察，不涉水追近，不用鱼饵把鸟引到危险处。", "记录水位、捕食和停留，鱼池防护避免使用会缠脚缠翅的松网。", "发现缠线或受伤个体先保持距离联系救助，长喙动物不要徒手抓。"], ["Observe wading and feeding while leaving safe retreat routes for people and birds.", "Stay at a shore observation point and do not chase into water or bait dangerous locations.", "Log water level and visits; pond protection must not entangle feet or wings.", "For line entanglement or injury, keep distance and contact help; do not grab a long-billed bird."]),
  鸡: profile("poultry", ["从干燥鸡舍、完整饲料和每日清点开始，兼顾群体内的弱鸡。", "按雏鸡或成鸡阶段准备饲料及保温方案，检查每只都能取水。", "投喂时逐只看精神、鸡冠和行走，及时收蛋并检查啄伤。", "某只长期被赶、缩头不动或不采食时先安排单独安全观察并咨询兽医。"], ["Start with dry housing, complete feed, and daily counts, including weaker flock members.", "Prepare feed and heating for chicks/adults and verify every bird can reach water.", "Inspect alertness, comb, gait, eggs, and peck injuries during routine visits.", "Persistent exclusion, huddling, or appetite loss needs safe separate observation and veterinary advice."]),
  鸭: profile("poultry", ["饮水清洁和休息区干燥要同时做到，不让舍内整天湿滑。", "按年龄准备适合鸭的饲料、饮水和防滑地面，幼鸭用水深度需另核对。", "查看鼻孔、眼部、足底和行动，清走湿料与湿垫料。", "跛行、胸腹持续脏湿或饮水异常时先查地面、排水与水器并就医评估。"], ["Keep drinking water clean while retaining dry, non-slip resting space.", "Use age-appropriate duck feed/water and flooring; review duckling water depth separately.", "Check nostrils, eyes, feet, and movement and remove wet feed/bedding.", "For lameness, persistently dirty wet plumage, or drinking changes, inspect flooring/drainage and seek veterinary assessment."]),
  鹅: profile("poultry", ["规划放牧活动、补饲和安全回舍，别只依赖草地自给。", "确认草地无危险杂物或有毒植物，设置清水、遮阴和夜间舍。", "观察食草与补饲情况，查看脚部和群体追赶，保持行走通道安全。", "生长慢、体况下降或持续争斗时重新核对日粮、空间与健康状态。"], ["Plan grazing, supplementary feed, and safe housing rather than relying on grass alone.", "Check pasture for hazards/toxic plants and provide water, shade, and night shelter.", "Observe grazing/feed intake, feet, and chasing and keep walking routes safe.", "For poor growth, condition loss, or conflict, review ration, space, and health."]),
  兔: profile("rabbit", ["每天看吃进去多少、排出来多少，比只看食盆是否满更有用。", "稳定原来食物后逐步调整，提供干草、清水和安全啃咬活动，不仅限小笼。", "记录便粒数量与大小、食欲和活动，清理臀部周围不洁并检查足底。", "突然不吃、便量骤减、腹部明显不适应尽快就医，不等几天观察。"], ["Actual intake and droppings matter more than a full food bowl.", "Stabilize the previous diet before gradual changes; provide hay, water, safe chewing, and exercise beyond a small cage.", "Track dropping size/number, appetite, and activity and inspect rear cleanliness and feet.", "Sudden appetite loss, sharply reduced droppings, or abdominal discomfort needs prompt veterinary care."]),
  鹌鹑: profile("poultry", ["地面清洁、躲藏和防惊跳比高栖架更适合作为照护重点。", "核对种类与年龄需求，提供防滑地面、隐蔽处和不易受惊撞伤的空间。", "查看足底、羽毛和取食，安静收蛋并清除潮湿垫料。", "头顶撞伤、啄伤或持续躲藏时先减少惊扰、检查空间并隔离受伤个体就医。"], ["Focus on clean ground, cover, and protection from startled jumps rather than high roosts.", "Confirm species/age needs and provide non-slip ground, cover, and space that limits collision injury.", "Inspect feet, feathers, and feeding, collect eggs quietly, and clear wet bedding.", "For head collisions, peck injuries, or hiding, reduce disturbance, inspect space, and seek care for injured birds."]),
  羊: profile("livestock", ["先分清绵羊或山羊，日粮、围栏和矿物补充不能直接照搬。", "确认种类、年龄与用途，核对草料和适用矿物料，准备干燥休息区。", "看反刍、食欲、步态与粪便，分别记录个体体况，不只看群体总采食。", "跛行、明显腹胀或持续离群时及时请兽医，不随意共用牛或马的矿物料。"], ["Distinguish sheep from goats; ration, fencing, and mineral supplements differ.", "Confirm species, age, and purpose and check forage/mineral suitability and dry resting space.", "Observe rumination, appetite, gait, and manure and record individual condition.", "For lameness, bloating, or isolation, contact a vet; do not casually share cattle/horse mineral feeds."]),
  猪: profile("livestock", ["饮水是否真正可用、地面是否干燥，往往比多加一顿料更先检查。", "测试饮水嘴实际出水，准备遮阴通风、干燥卧区及按阶段配制的饲料。", "比较每天饮水和剩料变化，查看躺卧、喘气、争食及地面湿滑。", "突然少饮或多饮时先复核饮水器、漏水和环境，再联系兽医分析伴随症状。"], ["Check functioning water and dry flooring before simply adding feed.", "Test nipple flow and provide shade, airflow, dry lying space, and stage-appropriate feed.", "Compare water/feed leftovers and observe lying, panting, competition, and slippery floors.", "For sudden intake changes, verify drinkers, leaks, and conditions, then discuss accompanying signs with a vet."]),
  牛: profile("livestock", ["用固定巡查记录采食、反刍和行走，日粮随阶段由专业人员核对。", "检查饮水、饲槽和防滑通道，保证个体能到达，并留安全操作退路。", "逐头观察站卧、反刍和蹄部，记录产奶或体况的明显变化。", "明显腹胀、倒地或急性呼吸异常需立即联系兽医，不自行灌药尝试。"], ["Use consistent intake, rumination, and gait checks with a professionally reviewed stage-specific ration.", "Inspect reachable water/feed, non-slip routes, and a safe handling escape route.", "Observe standing/lying, rumination, and feet individually and note milk/condition changes.", "Marked bloat, collapse, or acute breathing problems need immediate veterinary help, not improvised drenching."]),
  马: profile("livestock", ["稳定的草料、饮水、运动和蹄部检查构成每日基础。", "核对围栏、草料来源及安全饮水，日粮调整逐步进行并由专业人员评估。", "查看食欲、粪便、行走与蹄部，按实际活动安排照护交接。", "反复回看腹部、翻滚、出汗且不进食等异常应及时联系兽医，不自行喂药或强迫运动。"], ["Daily basics are consistent forage, water, exercise, and foot checks.", "Review fencing, forage source, and water; adjust rations gradually with professional input.", "Observe appetite, manure, gait, and feet and arrange care around actual activity.", "Repeated flank watching, rolling, sweating, or not eating needs prompt veterinary advice, not improvised medicine or forced exercise."]),
};
const foodProfiles: Record<string, Profile> = {
  果酱: profile("food", ["区分冷藏果酱与常温罐藏果酱，保存方式要在开做前选定。", "选用对应水果、果胶类型和保存方式的验证配方，称量果肉、糖及酸；不要直接减糖后仍按原法罐藏。", "按配方煮制与装瓶，记录原料净重、果胶类型及处理时间；小份冷藏和罐藏分别标记。", "不凝固是质量问题，鼓盖或霉变是安全警讯；后者不要靠再煮继续食用。"], ["Decide on refrigerated versus shelf-stable jam before starting.", "Use a tested recipe for the fruit, pectin, and storage method; weigh fruit, sugar, and acid without reducing sugar while retaining the original canning method.", "Follow cooking/packing steps and log net fruit weight, pectin, and process time; label refrigerated and canned portions separately.", "Failure to set is a quality issue; swelling or mold is a safety warning and not a reason to reboil and eat."]),
  梅子蜜: profile("food", ["梅子糖渍液不应自动视为常温安全或已经完成发酵。", "选无霉变果实，记录糖与果实净重、所用可靠冷藏工艺；不把蜂蜜版与糖版随意互换。", "按确定工艺管理冷藏和接触器具，分次取用，标记开封时间。", "非预期产气、鼓盖、黏滑或霉点时不要试尝，也不把冒泡解释成一定有益。"], ["Sugared-plum syrup is not automatically shelf-stable or a completed fermentation.", "Use sound fruit and record fruit/sugar weights and a reliable refrigerated method; honey and sugar versions are not interchangeable by assumption.", "Follow the chosen refrigeration method, use clean utensils, and label opening time.", "Unexpected gas, swelling, slime, or mold means no tasting; bubbles are not automatically beneficial."]),
  果汁: profile("food", ["鲜榨不等于无菌，清洗与冷藏也不能替代有效的杀菌工艺。", "丢弃腐烂果实，清洁榨汁器并分开生料接触工具；先选择适当的加工和保存方式。", "小量制作，及时按可靠方法处理和冷藏，不把上次剩汁混入新汁。", "给儿童、孕妇、老人或免疫力较弱者，优先选择经过巴氏杀菌等有效处理的果汁。"], ["Freshly squeezed is not sterile; washing and chilling do not replace an effective pathogen-reduction process.", "Discard spoiled fruit, clean the juicer, separate raw-contact tools, and choose an appropriate processing/storage method.", "Make small amounts, process/chill promptly by a reliable method, and do not mix leftovers into a new batch.", "For children, pregnant people, older adults, or those with weakened immunity, choose pasteurized or otherwise effectively treated juice."]),
  腌渍: profile("food", ["先区分醋腌和乳酸发酵，两种工艺不能随意交换比例。", "选择对应蔬菜的验证配方；称重，核对醋的标示酸度，不用自酿醋替代已知酸度醋。", "保持配方的食物、盐、醋和水比例，按要求压料或热处理，记录开始与冷藏日期。", "表面霉变、黏滑或关键比例不明时整份停止食用；不能靠尝到酸味证明安全。"], ["Distinguish vinegar pickling from lactic fermentation; their proportions are not interchangeable.", "Use a tested recipe for the vegetable, weigh ingredients, and verify labeled vinegar acidity rather than substituting homemade vinegar.", "Keep specified food/salt/vinegar/water proportions and required submersion or heating and log start/chilling dates.", "Mold, slime, or unknown critical proportions means stop consumption; a sour taste cannot establish safety."]),
  干制: profile("food", ["控制切片厚度、干燥过程和冷却后包装，避免表面干而内部仍湿。", "使用对应食材的干燥方法，切片尽量均匀、单层摆放；肉类不能套用水果方法。", "检查不同托盘与较厚部分，按方法完成干燥后冷却再包装，避免热装产生凝水。", "包装内出现凝水、返潮或霉变先停止食用并检查工艺，发霉部分不能只挑掉。"], ["Manage even thickness, drying, and cooled packing to avoid a dry exterior with a wet center.", "Use a method for that food, cut evenly, and arrange a single layer; fruit methods do not apply to meat.", "Check trays and thick pieces and complete the method before cooling and packing to avoid condensation.", "Condensation, dampness, or mold calls for stopping use and reviewing the process; do not just pick off mold."]),
  臭卤菜: profile("ferment", ["“臭味正常”不是安全依据，老卤尤其需要明确来源和经过验证的工艺。", "没有可验证的卤液来源、温度和处理流程时不要启动家庭自然发酵；可改用正规成品卤料的配套做法。", "原卤、处理原料和成品用具分开，记录每次加入物，禁止把不明剩料反复续入。", "批次记录缺失或出现非工艺预期的产气、黏滑和霉变时停止使用，煮沸不保证消除所有风险。"], ["An expected strong odor does not establish safety; old brines need traceability and a validated process.", "Do not start spontaneous home fermentation without verifiable brine, temperature, and process controls; use a reputable prepared product with instructions instead.", "Separate brine, raw-material, and finished-food utensils and log every addition; never keep adding unknown leftovers.", "Missing controls or unexpected gas, slime, or mold means stop use; boiling does not guarantee removal of every hazard."]),
  腐乳: profile("ferment", ["要分清受控接种与自然长霉，白色外观不能证明菌种安全。", "只能采用明确的食品用菌种和配套验证工艺；缺少控温、卫生和成熟条件时优先选可靠成品。", "把原料、菌种批号、温度及盐量逐项记录，避免其他食物与容器交叉接触。", "菌种不明、颜色异常或过程失控时不要试吃，不用刮掉表面继续腌制。"], ["Controlled inoculation is different from spontaneous mold; white growth does not identify a safe culture.", "Use only a defined food culture with a validated process; choose a reputable finished product if temperature/hygiene/maturation cannot be controlled.", "Record raw ingredients, culture lot, temperature, and salt and prevent cross-contact with other foods/vessels.", "Unknown cultures, abnormal colors, or failed controls mean no tasting or scraping off the surface to continue."]),
  豆豉: profile("ferment", ["制曲、盐渍和成熟各有控制点，不应只凭豆子变色判断成功。", "选定有明确食品菌种与操作条件的工艺，先备称量和温度记录，再处理豆料。", "分别记下制曲与后处理时间，按原方法处理通气和盐分，不随意混入老批次。", "非预期霉斑、污染或温度失控时停止用于食物；不把深色自动当作成熟。"], ["Culture growth, salting, and maturation have separate controls; color alone is not success.", "Choose a process with a defined food culture and conditions and prepare weighing/temperature records before the beans.", "Log culture and finishing stages separately and follow aeration/salt controls without mixing old batches.", "Unexpected mold, contamination, or lost temperature control means stop food use; dark color alone does not prove maturity."]),
  豆瓣酱: profile("ferment", ["豆料制曲与后续酱醅发酵不能省略关键比例和温度控制。", "确定豆、辣椒、盐和菌种的验证配方，原料清理与接种工具分开。", "逐项记录投料重量和翻动时间，容器防虫防污染，按工艺管理液面。", "用晒太阳、加盐或去霉覆盖过程失控并不可靠；有疑问不作为可食成品。"], ["Bean culturing and mash fermentation require the specified proportions and temperature controls.", "Choose a validated bean/chili/salt/culture recipe and separate raw preparation from inoculation tools.", "Log ingredient weights and mixing times, exclude insects/contamination, and manage the surface as specified.", "Sun, extra salt, or mold removal cannot validate a failed process; do not treat a questionable batch as edible."]),
  酱油: profile("ferment", ["制曲和酱醪成熟是受控过程，不是把豆子泡咸水即可。", "没有稳定菌种、卫生和工艺条件时不建议从自然接种开始；先明确原料、盐水与成熟流程。", "记录每个阶段的称量和温度，取样用洁净工具，按原工艺安排后处理。", "仅靠咸味、颜色或闻香不能确认安全；异常批次不与正常酱油混合。"], ["Koji and mash maturation are controlled processes, not simply beans in salty water.", "Do not start with spontaneous inoculation without reliable culture, hygiene, and controls; define ingredients, brine, and maturation first.", "Log weights and temperatures by stage, sample cleanly, and follow the specified finishing process.", "Saltiness, color, or aroma cannot establish safety; never blend a suspect batch into good sauce."]),
  醋: profile("ferment", ["酸味或家用pH读数都不等同于可用于安全罐藏的醋酸浓度。", "使用明确食品菌种与验证工艺，按方法保留所需通气，容器需食品接触适用。", "记录原料和转化过程，防虫防污染；作为腌渍或罐藏原料时选标示酸度合适的商品醋。", "自酿醋酸度未经验证时不要替代安全配方中的标准醋，也不靠多加一点来估算。"], ["Sourness or a home pH reading is not the acid concentration needed for safe canning.", "Use a defined food culture and validated method with required aeration and food-contact-suitable vessels.", "Log ingredients and conversion and prevent insects/contamination; use appropriately labeled commercial vinegar for pickling/canning.", "Do not substitute unverified homemade vinegar for standard-acidity vinegar or guess by adding more."]),
  果酒: profile("brew", ["原料、酵母、温度与排气要同时管理，不把密封水果糖罐当酿酒设备。", "用无霉变水果与明确酵母，准备适合发酵的食品容器、气锁和检测工具。", "记录糖量、发酵温度及比重趋势，按工艺管理果帽和转移，减少开盖污染。", "持续产气时勿密闭装瓶；容器异常鼓胀、霉变或原料不明时停止操作并安全处置。"], ["Manage fruit, yeast, temperature, and venting; a sealed fruit/sugar jar is not brewing equipment.", "Use sound fruit, defined yeast, a food-safe fermenter, airlock, and testing tools.", "Log sugar, temperature, and gravity trends and follow cap/transfer management with minimal contamination.", "Do not seal bottles during active gas production; stop for unusual pressure, mold, or unknown ingredients."]),
  米酒: profile("brew", ["酒曲类型、米饭处理与温度控制决定过程，不能仅凭甜味和出酒判断。", "采用来源明确的食品酒曲及其可靠工艺，备好称量、温度计和清洁发酵容器。", "记录米、水、酒曲重量与接种时温度，保持所需排气，按工艺及时结束或冷藏。", "非预期霉色、异味或关键温度失控时不要尝试；甜米酒也可能含酒精。"], ["Starter type, rice preparation, and temperature matter; sweetness or liquid appearance is not enough.", "Use a traceable food starter with a reliable method and prepare scales, a thermometer, and a clean fermenter.", "Log rice, water, starter weights, and inoculation temperature, allow required venting, and finish/chill as specified.", "Do not taste unexpected mold, odors, or a temperature-control failure; sweet rice wine may still contain alcohol."]),
  其他: profile("food", ["先写清正在做哪种食物和打算怎么保存，再选择对应的安全工艺。", "把食物名、原料、加工方法与保存目标写入项目，找到适用于该食品的可靠做法。", "记录关键重量、时间和储存条件；没有成熟工艺时先做少量即食，不扩展成长期保存。", "涉及低酸罐藏、真空常温保存或不明发酵时，不用其他食物的经验替代验证。"], ["Name the food and intended storage before selecting a safe process.", "Record food, ingredients, method, and storage goal and find a reliable method for that food.", "Log critical weights, times, and storage; without an established method, do not extrapolate a small fresh dish into long-term storage.", "For low-acid canning, room-temperature vacuum storage, or unknown fermentation, another food's experience is not validation."]),
};

export function getPracticalGuideContent(entry: PublicGuideEntry, language: PublicGuideLanguage): PublicGuideContent | null {
  if (entry.source !== "preset") return null;
  if (entry.category === "system") {
    const soilContent = getSoilGuideContent(entry.name, language);
    if (soilContent) return soilContent;
  }
  if (entry.category === "other") {
    const example = getPracticalFoodExample(entry.name, language);
    if (example) return example;
  }
  const profiles = entry.category === "system" ? facilityProfiles : entry.category === "insect_fish" ? ecologyProfiles : entry.category === "other" ? foodProfiles : null;
  const selected = profiles?.[entry.name];
  if (!selected) return null;
  const [overview, start, care, issue] = selected[language];
  const routine = routines[selected.kind];
  const nameReferences: Record<string, ReferenceKey[]> = { 龟: ["terrapin"], 果酱: ["jam"], 果汁: ["juice"], 干制: ["dry"], 蝴蝶: ["butterfly"], 毛毛虫: ["butterfly"], 猪: ["livestock"], 马: ["horse"], 羊: ["sheep"], 高床: ["structure"], 水循环过滤: ["fish"], 鱼缸鱼池: ["fish"] };
  const extraReferences = nameReferences[entry.name] || [];
  return {
    overview,
    parameters: [],
    cycle: null,
    sections: [
      { title: language === "en" ? "Start here" : "开始前与操作", items: [start, localize(routine.start, language)] },
      { title: language === "en" ? "Routine care" : "日常照护与维护", items: [care, localize(routine.care, language)] },
      { title: language === "en" ? "If something changes" : "异常先看这里", items: [issue] },
      { title: language === "en" ? "When to check" : "检查提醒", items: [localize(routine.reminder, language)] },
    ],
    cautions: [localize(routine.caution, language)],
    sources: [...new Set([...routine.references, ...extraReferences])].map((key) => references[key]),
  };
}
